### PR TITLE
Fix focus on main elements in Modern UI

### PR DESCRIPTION
**Pull request by tsynik**
This PR adds D-PAD navigation for Android TV devices and set-top boxes, etc

### CODE REVIEW

**Comment by topjohnwu** [comment]
@tsynik please let me know once your PR is complete

**Comment by tsynik** [comment]
> @tsynik please let me know once your PR is complete

@topjohnwu now it's probably complete. All main elements and buttons can be reached with D-PAD, but I don't know how to deal with radio buttons in button group and with options for settings in RecyclerView.
You can check behaviour in Emulator with D-PAD enabled

**Comment by tsynik** [comment]
I mean this blocks: https://imgur.com/a/k1hIyr5

**Comment by tsynik** [comment]
@topjohnwu last commit fixes Settings options select at least on Android till 7.1.2.
Magisk Manager till have issue with radio buttons on Install (2nd step). According to this post: https://stackoverflow.com/questions/43267741/getting-the-focus-of-the-radio-button-in-the-radio-group we need custom onFocusSearch or similar function for it. Or can they be changed to Checkboxes? After last commits in main branch for that blocks there is also style issues for text color (too light on light themes now on some android versions)

**Comment by tsynik** [comment]
OK, now it's full functional with remote at least on Fire TV 4K ;-)

**Comment by tsynik** [comment]
@topjohnwu those restored styles fixes unreadable text for install options

**Review by Nagatoemsohet — APPROVED** [review]

**Review by Rowdy-code — APPROVED** [review]

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
