### PR TITLE
Fixup support for Nook HD, add support for Acclaim

### PR DESCRIPTION
**Pull request by worstperson**
This fixes and updates support for the Nook HD (hummingbird) and HD+ (ovation), and adds support for the Nook Tablet (acclaim).

### CODE REVIEW

**Comment by osm0sis** [comment]
I have a question regarding the Nook HD "new magic" and the Acclaim magic - are there different versions for recovery images? I know with the old "Green Loader" version there was also "Green Recovery".

**Comment by worstperson** [comment]
Acclaim magic is uniform, Nook HD uses "Red Loader" and Nook HD+ uses "Green Loader". TWRP3 built by amaces uses "eMMC recovery.img+secondloader for hummingbird" and "eMMC recovery.img+secondloader for ovation", just like the ROMs.

**Comment by osm0sis** [comment]
Thanks! I'll fix up support for AIK and AK2. :+1:

**Comment by worstperson** [comment]
It may be used in some old roms, I'm not certain, it does not apply to Magisk though. hashcode/amaces Lollipop ROMs use "Green Loader" for both HD and HD+, while Marshmallow+ ROMs from amaces/Unlegacy-Android use the new magic.

**Comment by airend** [comment]
> Does "Red Loader" need to be added to this PR then? I don't see any mentioning of it.

I think that it was only used in old recovery images, which need a slightly different loader.

**Comment by worstperson** [comment]
"Red Loader" is currently being used in official TWRP for ovation

**Comment by airend** [comment]
Yup, basically anything that uses the old LP device trees (our official TWRP images are stuck on those).

**Comment by osm0sis** [comment]
Last question, you say Accliam magic is uniform, and I see it's "BauwksBoot", so does that mean that's the same even for recovery? Or is there "BauwksRecovery" ? Thanks!

**Comment by osm0sis** [comment]
Looks like no, since I found TWRP still has "BauwksBoot" - so I think we're good: https://github.com/osm0sis/AnyKernel2/commit/c81b3d565843516661eaf54a74745f72ef3dfe3b 👍

**Comment by worstperson** [comment]
Yes, all acclaim boot and recovery images I've found(that are still up) use "BauwksBoot" @ 0x30.

**Pull request merged**
