### PR TITLE
Fix sepolicy rules dir is not found in recovery

### PR DESCRIPTION
**Pull request by reiryuki**
- /persist and /metadata are not mounted in recovery by default causing sepolicy rules dir to not be detected
- recovery mounting appears to have been completely removed in error from util_functions.sh with https://github.com/topjohnwu/Magisk/commit/16e4c67992ead7705d6c8b10bd200f300aad451a#diff-f8cb6ae933f02a7a542c3f84299aaa23d8241aca56580fd7dcb64a92bce47692
- bring recovery mounts of sepolicy rules dir locations to mount_partitions from the uninstaller

### CODE REVIEW

**Review by vvb2060 — CHANGES_REQUESTED** [review]
Move to mount_partitions()

**Comment by osm0sis** [comment]
Here's where it used to be:
https://github.com/topjohnwu/Magisk/commit/16e4c67992ead7705d6c8b10bd200f300aad451a#diff-bdd4b56a6d06be70a9865641c28b284bb0bd0a738f1814cd6adb53ae67830d70R39

**Comment by osm0sis** [comment]
Didn't need to understand all of it, just that the part I pointed you to is what we need:

```
if ! $BOOTMODE; then
  # Mounting stuffs in recovery (best effort)
  mount_name metadata /metadata
  mount_name "cache cac" /cache
  mount_name persist /persist
fi
```

**Comment by reiryuki** [comment]
Like these? https://github.com/topjohnwu/Magisk/pull/5794/commits/65856ab77823eeb7746aaa23446f6555cb9967c5

**Comment by osm0sis** [comment]
Yes and no, I said it should go in mount_partitions at the line I showed you in the last link.

**Comment by reiryuki** [comment]
Understood https://github.com/topjohnwu/Magisk/pull/5794/commits/f5e1f81e0513e41e8693005ec63e617452f83f62 👍

**Review by vvb2060 — APPROVED** [review]

**Comment by osm0sis** [comment]
Perfect! Thanks! Okay, now just to remove the corresponding lines from the uninstaller, since now mount_partitions handles it everywhere: https://github.com/topjohnwu/Magisk/blob/master/scripts/uninstaller.sh#L43-L48

**Comment by reiryuki** [comment]
Got it https://github.com/topjohnwu/Magisk/pull/5799/commits/e0749687bf590ab0ef0889a428b012d131fa0620 👍

**Comment by osm0sis** [comment]
Looks good, but that commit isn't in this pull request.. Did you put it on a different branch?

**Comment by reiryuki** [comment]
Sorry my fault, it's fixed now https://github.com/topjohnwu/Magisk/pull/5794/commits/93f810e109e3f9d23497546cdc3ab64f564873d0 👍

**Comment by osm0sis** [comment]
Pushed some cosmetic stuff. Will need a squash when it's merged but otherwise good to go! Thanks for catching the issue. 🙌

**Review by osm0sis — APPROVED** [review]

**Pull request merged**
