### PR TITLE
Add Full Command Logging feature into MagiskSU

### PR DESCRIPTION
**Pull request by WandersonKalil**
@yujincheng08 your proposed changes were added. Could you do a review?

The MagiskSU's integrity is intact with this pull request.

### CODE REVIEW

**Comment by WandersonKalil** [comment]
@osm0sis could you run CI for me?

**Comment by osm0sis** [comment]
> @osm0sis could you run CI for me?

Think it'll build this time? You need to test your builds on your PC before pushing new commits.

**Comment by vvb2060** [comment]
You wasted 8x6 hours of CI build time, I will not allow you to waste public resources again.

**Comment by WandersonKalil** [comment]
@vvb2060 The api 31 wasted 27 minutes to test. The issue is on api 33 and api 34 in "logd" infinite loop execution, not in my code. Thus, there is no sense in you closing my pull request.

**Pull request closed without merging**
