### PR TITLE
Add recent developments in SafetyNet to the docs

### PR DESCRIPTION
**Pull request by linuxandria**
https://twitter.com/topjohnwu/status/1237656703929180160
My summary: https://t.me/bromitewebview/121

### CODE REVIEW

**Comment by osm0sis** [comment]
Guys, he needs to fix the typo I pointed out, stop blindly approving things, it's counterproductive.

**Comment by linuxandria** [comment]
@osm0sis missed another typo? Corrected my first

**Comment by osm0sis** [comment]
@linuxandria, yup! Check the line note above. :+1:

**Comment by osm0sis** [comment]
@linuxandria, can you please squash the 3 commits into a single commit? Then it's good to go I think!

**Comment by linuxandria** [comment]
@osm0sis done

**Comment by topjohnwu** [comment]
SafetyNet docs are removed from official docs as I am not willing to continually update the instructions. Thank you for the contribution though, really appreciate it!

**Pull request closed without merging**
