### PR TITLE
Fix detecting su in Qiwi

### PR DESCRIPTION
**Pull request by umerov1999**

### CODE REVIEW

**Comment by skaforey** [comment]
Wow this looks like a simple fix, does it work? I suspect if it does, this would fix the same naive check that Microsoft InTune does.  For now I have been using tasker to run a script to rename /sbin/su to /sbin/mu when I need to open Outlook.

**Comment by auanasgheps** [comment]
I am surprised that this path was not already unmounted... Well done.

**Comment by skaforey** [comment]
I confirmed this worked by building magisk with this change, but once it's triggered, /sbin/su never gets relinked.....I think we need an additional change to relink

**Comment by skaforey** [comment]
Furthermore, not sure how to actually mount it back since the binary points to /root/<randomname> that doesn't seem to be stored anywhere.  I tried symlinking back to /sbin/magisk but that doesn't work I guess.

**Comment by skelletR** [comment]
Hi I have problem to detecting root the app hex Editor say.. Can not change shell, is your phone rooted? Stream closed

**Comment by topjohnwu** [comment]
This is not a proper way to hide Magisk, the changes are irreversible

**Pull request closed without merging**
