### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by fossdd**
closes https://github.com/topjohnwu/Magisk/issues/3950

The MR for F-Droid is ready to merge. But it would great if you could merge this and re-tag, so that your metadata can directly changed in your repo without going to F-Droid.

### CODE REVIEW

**Comment by vvb2060** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/3193a4d0315d33ba98f04601a1bab812893083b0

**Comment by fossdd** [comment]
Mh. Okay. Just as notice, if fastlane is included here you can change the descriptios right in your repo without opening a new MR.

**Comment by vvb2060** [comment]
We do not provide support for the F-Droid version.

**Comment by fossdd** [comment]
oh. your descision..

**Pull request closed without merging**
