### PR TITLE
Fix finding busybox binary

### PR DESCRIPTION
**Pull request by Displax**
Close https://github.com/topjohnwu/Magisk/issues/3493

### CODE REVIEW

**Comment by osm0sis** [comment]
Hmm I don't see why the -f would fail.. the new busybox script is still a file. 😕

**Comment by osm0sis** [comment]
Also I think the wrapper should be used still, since this will basically undo the recent Samsung fix that the wrapper was created for.

**Comment by tsynik** [comment]
> Hmm I don't see why the -f would fail.. the new busybox script is still a file. 😕

I think this related to this PR. With latest canary magisk installed, there is no /data/adb/magisk/busybox, so for example xposed-framework-magisk.zip module can't be installed from TWRP recovery, here is log:

```
I:operation_start: 'Flashing'
Installing zip file '/sdcard/xposed-framework-magisk.zip'
Checking for Digest file...
I:Update binary zip
I:Extracting updater binary 'META-INF/com/google/android/update-binary'
I:Zip does not contain SELinux file_contexts file in its root.
[amonet] Load microloader from recovery... 
[amonet] Remove boot patch...
[amonet] OK
I:Legacy property environment not used in updater.
xargs: /data/adb/magisk/busybox: No such file or directory
Updater process ended with ERROR: 127
```

**Review by tsynik — APPROVED** [review]
this works

**Comment by osm0sis** [comment]
No, I think a different way will need to be found that keeps the fix for Samsung kerels in https://github.com/topjohnwu/Magisk/commit/f9c7a4c933f6116e41d65856555d9114bdbaa674 intact.

You might be right that it could be related to the shebang, we'll need to investigate further.

CC: @Displax

**Comment by tsynik** [comment]
> No, I think a different way will need to be found that keeps the fix for Samsung kerels in [f9c7a4c](https://github.com/topjohnwu/Magisk/commit/f9c7a4c933f6116e41d65856555d9114bdbaa674) intact.
> 
> You might be right that it could be related to the shebang, we'll need to investigate further.
> 
> CC: @Displax

But this fix related only to util_functions.sh and recovery mode install, so it will keep Samsung fix intact.

**Review by edg84 — APPROVED** [review]

**Pull request closed without merging**
