### PR TITLE
Magisk Hide enable/disable scripts fix

### PR DESCRIPTION
**Pull request by DeicPro**
-Toolbox's ps doesn't show arguments, `--daemon` in this situation.

### CODE REVIEW

**Comment by Shadowghost** [comment]
I think you can close this one since the changes were already merged.

**Comment by DeicPro** [comment]
@Shadowghost Not merged too, IDK that you mean.

**Comment by Shadowghost** [comment]
Your commits weren't merged but the changes were made. Take a look at the files. Or are the Beta builds by you and strangi explicitly including this PR? If yes, sorry for the inconvenience.

**Comment by DeicPro** [comment]
@Shadowghost yeah
https://github.com/stangri/MagiskFiles/blob/master/build.sh#L25

And you can look at this repo that the files haven't got that changes too
https://github.com/topjohnwu/Magisk/blob/624b7616d082feced71bff0474c64c1b4afd5cc0/scripts/magic_mask.sh#L92
https://github.com/topjohnwu/Magisk/blob/624b7616d082feced71bff0474c64c1b4afd5cc0/zip_static/common/magiskhide/enable#L15
https://github.com/topjohnwu/Magisk/blob/624b7616d082feced71bff0474c64c1b4afd5cc0/zip_static/common/magiskhide/disable#L14

**Comment by topjohnwu** [comment]
The scripts are not running in a subshell because someone would love the scripts to be run in a blocking way (meaning, boot will not continue until the scripts are done)
The service.sh scripts however, will not be blocking.

However your PR for magiskhide is nice, I'd love to include them
You can remove the subshell part, and I'll merge your changes

**Pull request merged**
