### PR TITLE
Enable verbose logs for modules in the repository

### PR DESCRIPTION
**Pull request by MarcAnt01**
That would be useful to grab additional information from logs, without having to modify the binary file manually.
Thanks to @JohnFawkes for making me aware of this command

### CODE REVIEW

**Comment by osm0sis** [comment]
Useful for debugging, sure, but no.. I don't think we want or need to see every single command fly by in Magisk Manager during every install.

**Comment by topjohnwu** [comment]
Closed as reasoned by @osm0sis

**Comment by MarcAnt01** [comment]
@topjohnwu @osm0sis no, the content will be shown just in the logs, the content in Magisk Manager won't be printed

**Comment by osm0sis** [comment]
Still, massive logs.

**Comment by MarcAnt01** [comment]
> Still, massive logs.

Yes, but aren't the logs meant to have as much information as possible. The standard Magisk logs rarely provide enough information

**Comment by JohnFawkes** [comment]
Just do

set -euxo pipefail
trap 'exxit $?' EXIT

In your install.sh with the functions

cancel() {
  imageless_magisk || unmount_magisk_img
  abort "$1"
}

exxit() {
  set +euxo pipefail
  [ $1 -ne 0 ] && cancel "$2"
  exit $1
}

**Comment by JohnFawkes** [comment]
This will enable logging and make your scripts fail loudly if there's any issue

**Comment by MarcAnt01** [comment]
> Just do
> 
> set -euxo pipefail
> trap 'exxit $?' EXIT
> 
> In your install.sh with the functions
> 
> cancel() {
> imageless_magisk || unmount_magisk_img
> abort "$1"
> }
> 
> exxit() {
> set +euxo pipefail
> [ $1 -ne 0 ] && cancel "$2"
> exit $1
> }

Thank you, thought there was no other way

**Comment by JohnFawkes** [comment]
There's multiple ways. However the above code will likely make your install fail until you fix stuff. For example if you have a variable that isn't set it will fail. Without the above code it wouldn't fail

**Pull request closed without merging**
