### PR TITLE
Add "sepolicy_custom"

### PR DESCRIPTION
**Pull request by RikkaW**
Huawei kernel only accepts sepolicy for once. So if we need to add custom SELinux rules, the only choice is to compile Magisk with new rules.

There are already multiple projects/apps require different rules, so I choose to create a custom mechanism. And the reason for not choose to open pull requests to add rules is it's inappropriate to add rules related to untrusted_app.

The change is simple, read sepolicy_custom in `early_mount` and use sepolicy_custom in `patch_sepolicy` if exists.

The user needs to use the ["custom sepolicy installer"](https://github.com/RikkaApps/magisk-custom-sepolicy-installer). It's modified from Magisk installer. On install, it generates sepolicy_custom using the `magiskpolicy` tool and adds sepolicy_custom to boot img. So devs only need to provide zips with their own rules.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you please rebase instead of merge master into this PR? This is really really noisy and break git graph.

**Comment by XspeedPL** [comment]
Are there any official plans regarding this?
A few people would love to see this included.

**Comment by gyj1109** [comment]
Are there any new progress?

**Comment by topjohnwu** [comment]
I am working on a complete new implementation, this PR will be kept open until it is added officially.

**Comment by Evengard** [comment]
Waiting for it, because newer versions of EdXposed migrated already to this new system, it just won't boot on the official Magisk ending up in a bootloop and I don't want to install an older Magisk with the patches... So I'm stuck on an older version.

**Pull request closed without merging**
