### PR TITLE
Allow unsupported version upgrades

### PR DESCRIPTION
**Pull request by vvb2060**
Magisk Manager allows install Magisk with other su,  just regard the unsupported Magisk as other su.

### CODE REVIEW

**Comment by gypise** [comment]
I can not get magisk to install on my phone. I have  LG PHONE MODEL LML414DL  Straighttalk phone. It is brand and still locked. Please Please help me to Root my phone. I have sever COPD and can not afford to buy a other phone my money goes to my meds doctors and hospital.

**Comment by harleyusa** [comment]
I can't get magisk to work no matter what i do i even tried to flash it but nothing works. Can someone pls help me....tyvm

**Comment by junborado5276** [comment]
$\:

**Comment by topjohnwu** [comment]
There is currently no plan to support other root solutions

**Comment by osm0sis** [comment]
@toojohnwu, that's not what this pull request was.

**Comment by topjohnwu** [comment]
Oh I see now, I'll try to make this more clear now

**Pull request closed without merging**
