### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by RenateUSB**
Adding one more way to circumvent a bad module.

### CODE REVIEW

**Comment by yujincheng08** [comment]
As said, incorrect. You dont have permission to set this prop.

**Comment by RenateUSB** [comment]
I just recovered my device doing this. Without root on a stock boot image.

**Comment by yujincheng08** [comment]
AVD 14: `type=1107 audit(1702305444.484:70): uid=0 auid=4294967295 ses=4294967295 subj=u:r:init:s0 msg='avc:  denied  { set } for property=persist.sys.safemode pid=6178 uid=2000 gid=2000 scontext=u:r:shell:s0 tcontext=u:object_r:safemode_prop:s0 tclass=property_service permissive=0'`

**Comment by yujincheng08** [comment]
okay. but still it does not work on AVD 14.

**Pull request closed without merging**
