### PR TITLE
Add Multiplexing  feature  support  into MagiskSU

### PR DESCRIPTION
**Pull request by WandersonKalil**
This is the native support. @topjohnwu will need to add support into the Magisk app to read and show the log_fd contents. For full details, see #7738 

With this pull request, Magisk is now on able to  log all root commands sent by all root apps to the /system/bin/sh shell.

### CODE REVIEW

**Comment by WandersonKalil** [comment]
@yujincheng08 cold you please do a first review into the code and test it on your device?

**Review by WandersonKalil — COMMENTED** [review]
@topjohnwu could you take time to review and test the current changes? This pull request is ready to review.

**Comment by WandersonKalil** [comment]
@topjohnwu Could you merge this pull request today and release a canary release?

**Review by WilmarE — COMMENTED** [review]
### 12344###

**Comment by osm0sis** [comment]
You haven't even gotten it to successfully build yet. So how about you stop asking for things until you have.

**Comment by WandersonKalil** [comment]
@topjohnwu this pull request is ready for Review.

**Comment by osm0sis** [comment]
No it's not, look at all the tests it's failing still.

**Comment by WandersonKalil** [comment]
> No it's not, look at all the tests it's failing still.
> 
> Until everything passes below nobody will even consider reviewing it.

Theo code itself was successfully compiled and works without any problem. The failing is on api 24 and above for some unknown reason. But the code is perfect and elegible to be merged.

**Comment by osm0sis** [comment]
It's your job to figure out those reasons.

**Comment by WandersonKalil** [comment]
@osm0sis Ok. The failing on api 24 and above is occurring  on AVD test itself, not in MagiskSU. Thus, this code may be merged without any issue. Believe in myself, I tested the code several times before uploading to GitHub. And, as already  stated, everything is working as espected.

**Comment by vvb2060** [comment]
#7792

**Comment by WandersonKalil** [comment]
@vvb2060 

> #7792 Your device is now failing like avd, please fix it.

The bug is in MagiskSU without this this changes.

**Comment by vvb2060** [comment]
#7794 Your device is now failing like avd. If you can't fix it, we'll just have to close pr

**Comment by WandersonKalil** [comment]
> > Magisk 81725b2(26405) daemon started
> 
> #7794 Your device is now failing like avd. If you can't fix it, we'll just have to close pr

@vvb2060 again, this pull request is working as expected.

**Comment by vvb2060** [comment]
This pr was closed due to continued ineffective communication.

**Comment by WandersonKalil** [comment]
> This pr was closed due to continued ineffective communication.

@vvb2060 This pull request is working  as expected. Please open it.

**Pull request closed without merging**
