### PR TITLE
Patch collection

### PR DESCRIPTION
**Pull request by vvb2060**

### CODE REVIEW

**Comment by sn-o-w** [comment]
I think you should remove commit **"skip mount modules at late_start stage"**. It seems like it causes bootloop. I tried all your commits, I got stucked in bootloop, then I reverted **"skip mount modules at late_start stage"** and now everything is fine (I use Magisk on a Nexus 5 running on Android 10 [Lineage OS 17.1])

**Comment by vvb2060** [comment]
@sn-o-w So, where is the problem? Can you provide logs? I'll see if I can fix it.

**Comment by sn-o-w** [comment]
> @sn-o-w So, where is the problem? Can you provide logs? I'll see if I can fix it.

I am not able to reproduce it anymore. Hmmm, not sure why tho. So for now everything is fine, just ignore my comment. If it happens again, I'll let you know and I'll get some logs.

**Comment by topjohnwu** [comment]
Removed commits that were cherry-picked/re-implemented.
The rest of the commits are still up for review.

**Review by edg84 — APPROVED** [review]

**Review by edg84 — APPROVED** [review]

**Comment by vvb2060** [comment]
https://github.com/vvb2060/Magisk/commits/alpha

**Pull request closed without merging**
