### PR TITLE
Default Toast Replaced With TastyToast

### PR DESCRIPTION
**Pull request by chankruze**
The default toast is now replaced with awesome tasty toast. The toast is now animated for success,error and info type response.
Better UI 😉

### CODE REVIEW

**Comment by chankruze** [comment]
My bad,
I got some compilation error.Let me fix these.

**Comment by MSF-Jarvis** [comment]
It's expected you provide screenshots when making UI related changes, makes the review process less cumbersome.

**Comment by chankruze** [comment]
@MSF-Jarvis Yeh Good Point !
Here Are The Screenshots !

**Comment by MSF-Jarvis** [comment]
Those look horrible...

**Comment by apkharsh** [comment]
These changes are really good. 
Thanks chankurze.

**Comment by DenyDarko** [comment]
That's cute. 😁

I like it 😄

**Comment by topjohnwu** [comment]
Thanks for the PR, but I think Magisk Manager don't need fancy toasts :)

**Comment by apkharsh** [comment]
The toasts doesn't looks fancy though. Looks cool.

**Comment by thanasxda** [comment]
speaking of horrible, change your profile pic.... people just jealous lolz

**Pull request closed without merging**
