### PR TITLE
Update spanish

### PR DESCRIPTION
**Pull request by peter9811**

### CODE REVIEW

**Comment by topjohnwu** [comment]
Thank you for the contribution, would you mind to also translate the strings introduced in [this commit](d76c266fbcc1ca9e7c62dc2767faabc78fa27920) too? Thank you very much!

**Comment by peter9811** [comment]
The pull show me "404"

But, yeah. No problem. I can help translating the new commits

**Comment by topjohnwu** [comment]
@peter9811 updated the previous comment

**Comment by peter9811** [comment]
@topjohnwu So, do I translate from in to es?
I will do it right now

**Comment by peter9811** [comment]
I think yep

**Pull request merged**
