### PR TITLE
flash module: ignore META-INF

### PR DESCRIPTION
**Pull request by vvb2060**
sync with `magisk --install-module`

### CODE REVIEW

**Comment by Amdre-afk** [comment]
[magisk_log_2024-09-29T00.13.00.log](https://github.com/user-attachments/files/17178331/magisk_log_2024-09-29T00.13.00.log)

**Review by Kimmon322 — COMMENTED** [review]
Leave 29

**Review by salvogiangri — COMMENTED** [review]
Commit d33b077a13b34691a7f1fd3643336e09383ced78 introduced a regression that causes modules which erroneously use a _very old_ version of the [module_installer.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh) script to not flash properly, it would be great to see this merged with the next release since it solves the issue

**Review by Jpac7-ai — COMMENTED** [review]
Magik

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
