### PR TITLE
No root access in manager

### LINKED ISSUE #754: MagiskManager6.0.1-9b063856的一些小问题
全新安装MagiskV17.4-ceb51bb1与MagiskManager6.0.1-9b063856并在非主用户第一次打开MagiskManager6.0.1-9b063856时会出现“需要额外安装”的提示，并且会失败

### PR DESCRIPTION
**Pull request by vvb2060**
fix #754

### CODE REVIEW

**Comment by vvb2060** [comment]
@topjohnwu 目前的代码，如果没有安装magisk，也没有root，会弹出提示，要求修复magisk……
真的不顾这个问题吗？为什么在没有root的情况下进行env_check？

**Comment by kirbyapps** [comment]
I found out with my Galaxy note 9 Verizon I need to download a recovery instead of magisk. I'm

**Comment by kirbyapps** [comment]
Leave the magisk  manager and flash a recovery. I was told I'd not root my note.... A senior member of XDA

**Comment by patrickschneider23** [comment]
- @kirbyapps

**Pull request closed without merging**
