### PR TITLE
magiskboot: Check dtb header content to avoid false positives

### PR DESCRIPTION
**Pull request by boeglin**
This fixes the issue described at:
https://forum.xda-developers.com/showpost.php?p=76726794&postcount=5719
https://forum.xda-developers.com/showpost.php?p=76734324&postcount=5723

### CODE REVIEW

**Comment by Limero** [comment]
This should be merged asap. Magisk won't work on OnePlus 5T with stock kernel and latest LineageOS without it.

**Comment by nekromant** [comment]
+1

**Comment by topjohnwu** [comment]
Thank you for your contribution!

**Comment by Limero** [comment]
@topjohnwu Thanks for merging. Any ETA on v16.5 with these fixes?

**Comment by auanasgheps** [comment]
@Limero If you want to test you build the source by yourself. John just came back from military service... We should let him work :)
I'm sure 16.5 will be out _soon_

**Pull request merged**
