### PR TITLE
Fix hide from applications in secondary profiles

### LINKED ISSUE #2181: Magisk Hide doesn't apply to packages not installed for user 0
Think of package `com.example.package` only installed for user 10 (work profile), the following code can't detect them as `/data/user_de/0/com.example.package` doesn't exist.

https://github.com/topjohnwu/Magisk/blob/3beffd84d654342b5a68900d2677972f539ddfb0/native/jni/magiskhide/proc_monitor.cpp#L82

### PR DESCRIPTION
**Pull request by a-ilin**
This fix allows to hide Magisk from applications installed
into secondary profiles only (on multi user devices).
In case of an application is installed into secondary profile,
all data subdirectories have to be checked, not only for user 0.
Also uid has to be consistent with the app package.

- Scan all user profiles for applications from hide_set
- Fix uid truncating for secondary profiles

Fixes #2181

### CODE REVIEW

**Comment by diegosucaria** [comment]
I would love to see this merged. Thanks !

**Comment by goodwin** [comment]
Is this going to be merged? Some of us have a Work profile, so this is relevant.

**Comment by saidmohamm** [comment]
شكرا لك

**Comment by osm0sis** [comment]
@topjohnwu, any reason that this can't be merged?

**Comment by damanptyltd** [comment]
@topjohnwu any blockers for this? Would great to have this merged so i can use magisk on my phone with work profile.

**Comment by fabdsp** [comment]
I would love to see this merged too. Thanks !

**Comment by a-ilin** [comment]
> 
> 
> @topjohnwu, any reason that this can't be merged?
> 
> @a-ilin, is this still confirmed working?

I tested the patch with Magisk v20.4 today, it still works.

**Comment by blastagator** [comment]
> > @topjohnwu, any reason that this can't be merged?
> > @a-ilin, is this still confirmed working?
> 
> I tested the patch with Magisk v20.4 today, it still works.

Care to share for additional testing, so I don't have to compile it myself?

**Comment by a-ilin** [comment]
> 
> 
> > > @topjohnwu, any reason that this can't be merged?
> > > @a-ilin, is this still confirmed working?
> > 
> > 
> > I tested the patch with Magisk v20.4 today, it still works.
> 
> Care to share for additional testing, so I don't have to compile it myself?

Sure, here is the archive:
[out.zip](https://github.com/topjohnwu/Magisk/files/4914359/out.zip)

I used those version numbers for build:
```
# The version name and version code of Magisk
version=20.9
versionCode=20999

# The version name and version code of Magisk Manager
appVersion=9.9.9
appVersionCode=999
```

**Comment by Unb9rn** [comment]
Any updates on this?
@topjohnwu this is still much needed feature to work with Shelter isolation. Thanks!

**Comment by RTS5227** [comment]
Hope it'll get merged soon.

**Comment by yukosky** [comment]
I hope it will merge into the Magisk source code in the future.

**Comment by yonkour** [comment]
> > > > @topjohnwu, any reason that this can't be merged?
> > > > @a-ilin, is this still confirmed working?
> > > 
> > > 
> > > I tested the patch with Magisk v20.4 today, it still works.
> > 
> > 
> > Care to share for additional testing, so I don't have to compile it myself?
> 
> Sure, here is the archive:
> [out.zip](https://github.com/topjohnwu/Magisk/files/4914359/out.zip)
> 
> I used those version numbers for build:
> 
> ```
> # The version name and version code of Magisk
> version=20.9
> versionCode=20999
> 
> # The version name and version code of Magisk Manager
> appVersion=9.9.9
> appVersionCode=999
> ```

Since using a work profile on my phone is very important to me and I also do not want to loose access to all the modifications on my phone, I decided to give this a try and it actually works (though I made a few mistakes when I was trying it out first and hence didnt work for me initially). Here are the steps for anyone else who might end up visiting this page. I hope at some point this will be merged and be available in latest magisk directly, but for now, I am using the build @a-ilin 's build from the quoted message. Also some of these steps might not even be necessary, I am just stating the things that I did and worked for me.

**Here were the steps that that helped me and might be useful if you are not used to it:**

1. Install the magisk-release.zip file from the above download. I did this through twrp
2. Uninstall regular magisk manager and install the above specified app (app-release.apk) from above download.
3. In Magisk Manager give root access to ADB (ie., in Settings set the "Superuser Access" to allow ADB).
4. In Magisk Manager change "Multiuser Mode" to "User-Independent" (not sure if necessary. Thats just what I am using in my testing).
5. Install the magisk manager app in work profile using adb shell. For this, I used the following commands (references that helped me with these commands: [install-apk-in-work-profile-via-adb-in-android](https://stackoverflow.com/questions/56951666/install-apk-in-work-profile-via-adb-in-android) and [apk-installation-failed-install-failed-verification-failure](https://stackoverflow.com/questions/15014519/apk-installation-failed-install-failed-verification-failure)):
   - Copy the apk to your phone: ```adb push app-release.apk /data/local/tmp```
   - Check the user id using: ```adb shell pm list users``` and note the userid for work profile. For me it was 11 but could be different for you
   - Now enter the adb shell using ```adb shell``` and all the following commands are inside the shell
   - Run superuser using ```su``` and now should be in superuser shell
   - (This is an optional command if you get an error while install the apk next. If you get a \[INSTALL_FAILED_VERIFICATION_FAILURE\] error, then you can run these commands in the shell):
       - ```settings put global verifier_verify_adb_installs 0```
       - ```settings put global package_verifier_enable 0```
   - Install the apk in work profile. For me my user id for work profile was 11. Can the command if you id is different: ```pm install --user 11 /data/local/tmp/app-release.apk```
6. At this point you should have 2 magisk managers installed, one for regular profile and one for work profile. Goto the Magisk Manager for the work profile and goto Magisk Hide and hide the work profile apps you want to hide. 


As Mentioned before, I am very new to this and some of these steps might be unnecessary (and/or there might be better ways of doing this). This is just supposed to help guide someone who might be new to this like me

**Pull request closed without merging**
