### PR TITLE
Update to APK Signature Scheme v2

### PR DESCRIPTION
**Pull request by vvb2060**

### CODE REVIEW

**Comment by topjohnwu** [comment]
The original code was specifically optimized for extreme low memory usage (on Android it can very easily trigger `OutOfMemoryError`). The code is also used to sign the release zip files and have to workaround some dumb recovery unzip implementations. This change will need further review/modification before it can be merged.

**Comment by osm0sis** [comment]
Does a signed zip still work with recovery unzip?

**Comment by jcgasca25** [comment]
> _No description provided._

https://github.com/topjohnwu/Magisk/pull/3055#issue-464656110

**Comment by jcgasca25** [comment]
https://github.com/topjohnwu/Magisk/pull/3055#issue-464656110

**Comment by topjohnwu** [comment]
@osm0sis the busybox in Magisk can unzip any valid zip file regardless of signed or not (no adjustment needed).
The v2 scheme seems to be doing similar stuff zipadjust is doing, so I would assume yes

**Comment by osm0sis** [comment]
Nice. Thanks. Figured it worked since nobody has complained. 😄

**Pull request merged**
