### PR TITLE
Support PATCHVBMETAFLAG env variable

### PR DESCRIPTION
**Pull request by vvb2060**
https://t.me/s/vvb2060Channel/577

https://cs.android.com/android/platform/superproject/+/master:external/avb/libavb/avb_vbmeta_image.h;l=177;drc=de53827b226bccef7407e4c253b0152e8d9f8e04

```cpp
  /* 120: Flags from the AvbVBMetaImageFlags enumeration. This must be
   * set to zero if the vbmeta image is not a top-level image.
   */
  uint32_t flags;
```

https://cs.android.com/android/platform/superproject/+/master:external/avb/libavb/avb_slot_verify.c;l=785;drc=c0debbfd55f08a755b006550779c23e707d30b6d
```cpp
  /* If we're the toplevel, assign flags so they'll be passed down. */
  if (is_main_vbmeta) {
    toplevel_vbmeta_flags = (AvbVBMetaImageFlags)vbmeta_header.flags;
  } else {
    if (vbmeta_header.flags != 0) {
      ret = AVB_SLOT_VERIFY_RESULT_ERROR_INVALID_METADATA;
      avb_errorv(full_partition_name,
                 ": chained vbmeta image has non-zero flags\n",
                 NULL);
      goto out;
    }
  }
```
If vbmeta partition exists, the vbmeta inside the boot image, flag must be 0

### CODE REVIEW

**Comment by osm0sis** [comment]
Just tested this out now that OnePlus 9 Pro on OOS 12 is an effected device. Seems a few usability problems/patching issues still.

1) I don't see an option to set KEEPVBMETAFLAG anywhere in the app manually for .img patching or direct install.

2) I prepatched an image manually with KEEPVBMETAFLAG=true in /.backup/.magisk and the AVBv2 flag hex edited to 00, but .img patching and direct install successfully read .magisk and kept it set true there (which is an improvement over 23015), but then it did not honor this in repack, so the AVBv2 flag still got set to 03 again.

**Comment by osm0sis** [comment]
Sounds like it'll be vbmeta partition patching for us all, after all!

f4ed6274a4c8294cc4804385bc29957f0a73934d

**Comment by i-sync** [comment]
Hello @vvb2060 @osm0sis 
MI10S , Android 11 , MIUI12.6 
I have the same problem with my phone.
How to set PATCHVBMETAFLAG=true?
Many thanks~

WeChat Image_20211217165232

**Comment by carey036** [comment]
> Hello @vvb2060 @osm0sis
> MI10S , Android 11 , MIUI12.6
> I have the same problem with my phone.
> How to set PATCHVBMETAFLAG=true?
> Many thanks~

any questions if set it false?

**Comment by i-sync** [comment]
Hi @carey036 
Thanks for your reply.

I have the same problem with my phone.
After installing magisk-patch-boot.img, the phone reboots infinitely

After checking the information, I found that it may be related to AVBv2 signature.
I found [https://github.com/topjohnwu/Magisk/issues/4447](https://github.com/topjohnwu/Magisk/issues/4447)
[](https://github.com/topjohnwu/Magisk/pull/5028)

So I want to try to see if setting PATCHVBMETAFLAG=true works

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
