### PR TITLE
Rename changes.md to sepolicy.rule

### PR DESCRIPTION
**Pull request by Karanragu**

### CODE REVIEW

**Comment by Gamemulatorer** [comment]
@osm0sis @Karanragu is spamming again 🤣🤣🤣

**Comment by Karanragu** [comment]
Sorry guide me install Magisk for root my device

**Comment by androidacy** [comment]
X-D-A.

I recommend you use that instead of spamming GitHub pull requests.

**Comment by Fox2Code** [comment]
You may want to close this PR.

If you really need to install Magisk, the install guide is here:
https://github.com/topjohnwu/Magisk/blob/master/docs/install.md
https://www.deepl.com/translator <- Also the is a translator for you if you struggle with English

As Androidacy said if you have still a problem installing Magisk XDA is the right place to go:
https://forum.xda-developers.com/f/magisk.5903/

Now stop making bogus Pull Requests here, because you will not get support on a pull request.

**Comment by osm0sis** [comment]
This is definitely a spam bot trying to not look like a spam bot since I reported it.

**Comment by osm0sis** [comment]
Pretty sure you wouldn't be posting all this bullshit if all you wanted was help installing Magisk.

**Pull request closed without merging**
