### PR TITLE
Add new Ianmacd and Monochrome themes.

### PR DESCRIPTION
**Pull request by ianmacd**
These two new high contrast themes offer improved legibility.

### CODE REVIEW

**Comment by linuxandria** [comment]
A much needed improvement :)

**Comment by osm0sis** [comment]
Please rename these after Pokemon to get merged. 😛

**Comment by ianmacd** [comment]
> Please rename these after Pokemon to get merged.

@diareuse can call them whatever he wants. I'm too old to know anything about Pokémon and too old to care.

**Comment by osm0sis** [comment]
Maybe Unown for monochrome? 😆

**Comment by topjohnwu** [comment]
@ianmacd I'll wait for the design to be final before merging any external theming PRs.
Also, I'm currently thinking of allowing customizations within the app itself, and maybe even allow creating profiles so themes can be shared.

**Pull request closed without merging**
