### PR TITLE
Add Dockerfile for build in docker

### PR DESCRIPTION
**Pull request by EvgeniyBlinov**
Tested only on:
```
./build.py -v ndk
./build.py -v all
```

### CODE REVIEW

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=event%3Apush

**Comment by EvgeniyBlinov** [comment]
> https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=event%3Apush

Can you explain the reason for closing the pull request, please?

**Comment by vvb2060** [comment]
We use the standard environment of GitHub Action to build apk and will not maintain other build environments.

**Comment by EvgeniyBlinov** [comment]
> We use the standard environment of GitHub Action to build apk and will not maintain other build environments.

What can you recommend for local build apk with fixed versions of dependencies?
Are the current build server settings (ansible, vagrant...etc) publicly available somewhere?
So that I can make an exact copy for local build.

**Comment by vvb2060** [comment]
#6675

**Pull request closed without merging**
