### PR TITLE
Retain PREINITDEVICE during A-only addon.d

### PR DESCRIPTION
**Pull request by osm0sis**
Just realized this was missing from our recovery dirty flash PREINITDEVICE support!

### CODE REVIEW

**Comment by osm0sis** [comment]
Adjusted the restore placement to be before the sleep 5 to ensure there aren't any potential timing issues that could result in config.orig getting removed.

Should be good to go now! 👍

**Comment by osm0sis** [comment]
This should have been merged before stable to avoid loss in function for A-only users... 🫤

**Review by topjohnwu — APPROVED** [review]

**Comment by osm0sis** [comment]
> I JUST installed 26.3 on such a device. What do I need to be careful about?

Install latest canary in a recovery and you're fine.

**Comment by osm0sis** [comment]
> Alright. Is it okay to go back to 26.1 though? I would much prefer staying on stable.

Not a good idea.

**Pull request merged**
