### PR TITLE
Fix various prop hide issues in MagiskHide

### PR DESCRIPTION
**Pull request by Fox2Code**
By checking props on @Fernixx Samsung phone I noticed that 
`ro.vendor.boot.warranty_bit` has the value `1`
So I made this patch to improve MagiskHide on some Samsung phones
(Including my friend phone)

### CODE REVIEW

**Comment by osm0sis** [comment]
Can you add the prop and value I mentioned from #2116 too, so both can be closed?

**Comment by Fox2Code** [comment]
Ok I will merge #2116 into my branch

**Comment by Fox2Code** [comment]
Done!
I let `unknown` as prop value because it seem more widespread than `normal`
On my phone _(LineageOS Pie)_ and on @Fernixx phone _(Stock OneUI Pie)_ the props are set to `unknown`

**Comment by osm0sis** [comment]
Hmm I guess we'll see if setting them to unknown has any effect on others

**Comment by Fox2Code** [comment]
Maybe changing the beaviour of props patching may be a solution

**Comment by topjohnwu** [comment]
@osm0sis on Pixel, it seems to be unknown

**Comment by Fox2Code** [comment]
Maybee changing the behavior of the prop patching may be a solution.
If for example `normal` or `unknown` it does nothing but if something else it detected it set the property to `unknown`

**Comment by Fox2Code** [comment]
Made a patch to handle the case where `ro.bootmode` or `ro.boot.mode` is set to `normal`
Since it should not affect the detection if the prop is `normal` rather than `unknown`
But I rather prefer setting the prop to `unknown` in other cases since it appear to be more common across many devices

**Comment by osm0sis** [comment]
Looks like maybe a better way to write the check for unknown and normal would be as they do in this PR?

https://github.com/topjohnwu/Magisk/pull/2470/files

**Comment by Fox2Code** [comment]
Yup I will change that and put value to `unknown` if `recovery` is detected

**Comment by Fox2Code** [comment]
Since we are no longer talking about `.warranty_bit` props I renamed the discussion

**Comment by osm0sis** [comment]
Looks good! Can you squash it all to one commit and add "Closes #2116" to your commit message to clean it up for @topjohnwu to merge it? :+1:

**Comment by Fox2Code** [comment]
Ok I mess up my local branch by trying to squash all commits together and made everything worse (First time I try to squash commits)
I will try again tomorrow but I promise nothing.

**Comment by Fox2Code** [comment]
:tada: Yeah I finally succeed to squash it all :tada: 
At least now I know how to make it
The problem was when I tried to squash It would take #2116 branch instead of master Magisk branch
I successfully find a workaround for the issue so it's fine now

**Comment by osm0sis** [comment]
Great! My only nitpick is the main commit name of "Squash commits" doesn't really explain what it does anymore. It should ideally be something more like your PR name, like "MagiskHide prop additions".

Otherwise, good to go for merge, @topjohnwu!

**Comment by Fox2Code** [comment]
Renamed the commit (The name it a bit longer because I put everything in title instead of description.)

**Pull request merged**
