### PR TITLE
Magisk

### PR DESCRIPTION
**Pull request by xXxrAinZyian**

### CODE REVIEW

**Comment by xXxrAinZyian** [comment]
Ok

**Comment by DarkPlayerr** [comment]
pro developer

**Comment by karthik558** [comment]
Bro

**Comment by ArixElo** [comment]
pero developer, teach me senpai

**Comment by uditkarode** [comment]
Apple is done for now. This is the change that will convert all iPhone users to rooted Android users.

**Comment by akyaruu** [comment]
huh... peru af debelob

**Comment by AntiEngineer** [comment]
You should be really braindead to really make such pull request.

**Comment by tesla59** [comment]
Google wants to hire u

**Comment by Vishalcj17** [comment]
bruh

**Comment by ShivamKumar2002** [comment]
Omg what an idea, why didn't anyone else think of it 😂

**Comment by Dialynx** [comment]
Omg you're so pru

**Comment by Dialynx** [comment]
Google wants to know your location

**Comment by Rasenkai** [comment]
Pro af sur

**Comment by KevinZonda** [comment]
Brilliant!

**Comment by chenaidairong** [comment]
This's so crazy

**Pull request closed without merging**
