### PR TITLE
Rename bootimgtools to magiskboot

### PR DESCRIPTION
**Pull request by Yeradon**
Renaming is missing within build.sh

### CODE REVIEW

**Comment by Yeradon** [comment]
a839cb787e564df2c4781649426ea915cd2a4129

**Comment by lexyan** [comment]
Hi Yeradon,
there is also reference to bootimgtools in the script directory, specially in  scripts/flash_script.sh

**Comment by Yeradon** [comment]
Yeah saw that when i tried to flash. Gonna trie to find them all. I don't know much details about magisk's internal structures so its more of a trial and error for me. Gonna add the rest when i found all direct and indirect references.

**Comment by Yeradon** [comment]
Ok a quick search showed that it's only used during un/installation process, which is what you expect. But when modifying the installer script, there is a 255 Error during installation. Which is not really helpfull,

**Comment by Yeradon** [comment]
Fixed by topjohnwu in lässt commits

**Pull request closed without merging**
