### PR TITLE
Optimize unzip for module installation

### PR DESCRIPTION
**Pull request by yujincheng08**
Previous ZipInputStream will decompress all entries even we don't use, and java.utils.ZipFile is too complex.
Use org.apache.commons.compress for better compatability.

### CODE REVIEW

**Review by downbadd — COMMENTED** [review]
,,👻

**Comment by admsev** [comment]
@gooroodev can you review this?

**Comment by gooroodev** [comment]
@admsev, thank you for the call!

| 🐞Mistake | 🤪Typo | 🚨Security | 🚀Performance | 💪Best Practices | 📖Readability | ❓Others |
|-----------|--------|------------|---------------|-------------------|---------------|-----------|
| 0         | 0      | 0          | 0             | 1                 | 1             | 0         |

### Summary of Proposed Changes
* ➕ Added `org.apache.commons:commons-compress:1.26.2` dependency.
* ➕ Replaced `ZipInputStream` with `org.apache.commons.compress.archivers.zip.ZipFile` for unzipping files.
* ➖ Removed `InputStream.unzip` extension function.
* 📖 Improved readability by simplifying the unzipping logic.
* 💪 Followed best practices by using a more robust and feature-rich library for handling ZIP files.

### Identified Issues
| ID  | Type            | Details                                                                 | Severity | Confidence |
|-----|-----------------|-------------------------------------------------------------------------|----------|------------|
| 1   | 💪Best Practices | `dest.parentFile!!` usage without null check in `ZipUtils.kt` lines 33, 34, 35 | 🟠Medium | 🟠Medium    |
| 2   | 📖Readability    | Nested `if` statements can be simplified in `ZipUtils.kt` lines 28-36    | 🟡Low    | 🟡Low       |

#### Issue 1
**ID:** 1

**Explanation:**
In `ZipUtils.kt` lines 33, 34, 35, the code uses `dest.parentFile!!` without checking if `parentFile` is null. This can lead to a `NullPointerException`.

**Code:**
```kotlin
dest.parentFile!!.let {
    if (!it.exists())
        it.mkdirs()
}
```

**Fix:**
```kotlin
dest.parentFile?.let {
    if (!it.exists())
        it.mkdirs()
} ?: throw IOException("Parent file is null for entry: ${entry.name}")
```

**Explanation of Fix:**
The fix adds a null check for `parentFile` and throws an `IOException` if it is null.

#### Issue 2
**ID:** 2

**Explanation:**
The nested `if` statements in `ZipUtils.kt` lines 28-36 can be simplified to improve readability.

**Code:**
```kotlin
if (!entry.name.startsWith(path) || entry.isDirectory) {
    // Ignore directories, only create files
    continue
}
val name = if (junkPath)
    entry.name.substring(entry.name.lastIndexOf('/') + 1)
else
    entry.name
val dest = File(folder, name)
dest.parentFile!!.let {
    if (!it.exists())
        it.mkdirs()
}
dest.outputStream().use { out -> zip.getInputStream(entry).copyAll(out) }
```

**Fix:**
```kotlin
if (entry.name.startsWith(path) && !entry.isDirectory) {
    val name = if (junkPath)
        entry.name.substring(entry.name.lastIndexOf('/') + 1)
    else
        entry.name
    val dest = File(folder, name)
    dest.parentFile?.let {
        if (!it.exists())
            it.mkdirs()
    } ?: throw IOException("Parent file is null for entry: ${entry.name}")
    dest.outputStream().use { out -> zip.getInputStream(entry).copyAll(out) }
}
```

**Explanation of Fix:**
The fix simplifies the nested `if` statements by combining conditions and ensuring the code is more readable.

### General Review
The proposed changes improve the performance and readability of the unzipping logic by using the `org.apache.commons.compress.archivers.zip.ZipFile` library. However, there are minor issues related to best practices and readability that need to be addressed. The use of `parentFile!!` without null checks can lead to potential `NullPointerException`, and the nested `if` statements can be simplified for better readability. Overall, the code quality and style are good, but addressing these issues will make the code more robust and maintainable.

--
I **only** arrive when I am mentioned and asked to review the pull request.
React or reply to let me know what you think!

**Comment by admsev** [comment]
@downbadd Gooroo's comment makes sense IMO

```
dest.parentFile?.let {
    if (!it.exists())
        it.mkdirs()
} ?: throw IOException("Parent file is null for entry: ${entry.name}")
```

**Pull request closed without merging**
