### PR TITLE
Support bootconfig

### PR DESCRIPTION
**Pull request by vvb2060**
https://android-review.googlesource.com/c/platform/system/core/+/1615298

/proc/bootconfig
```
hardware = "cutf_cvm"
kernel.mac80211_hwsim.radios = "0"
kernel.snd-hda-intel.enable = "0"
kernel.vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size = "16384"
androidboot.fstab_suffix = "f2fs"
androidboot.slot_suffix = "_a"
androidboot.force_normal_boot = "1"
androidboot.console = "invalid"
androidboot.boot_devices = "pci0000:00/0000:00:08.0", "pci0000:00/0000:00:09.0"
androidboot.cpuvulkan.version = "4198400"
androidboot.hardware.gralloc = "minigbm"
androidboot.hardware.hwcomposer = "ranchu"
androidboot.hardware.egl = "angle"
androidboot.hardware.vulkan = "pastel"
androidboot.serialno = "CFCVD10D9362DF54"
androidboot.lcd_density = "320"
androidboot.setupwizard_mode = "DISABLED"
androidboot.vsock_tombstone_port = "6600"
androidboot.cuttlefish_config_server_port = "6800"
androidboot.vendor.vehiclehal.server.cid = "2"
androidboot.vendor.vehiclehal.server.port = "9210"
androidboot.vendor.audiocontrol.server.cid = "3"
androidboot.vendor.audiocontrol.server.port = "9410"
androidboot.vsock_frames_port = "6900"
androidboot.modem_simulator_ports = "9200"
androidboot.wifi_mac_address = "40:1:2:3:4:1"
androidboot.verifiedbootstate = "orange"
```
/proc/cmdline
```
mac80211_hwsim.radios="0" snd-hda-intel.enable="0" vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size="16384" stack_depot_disable=on  printk.devkmsg=on firmware_class.path=/vendor/etc/ init=/init kfence.sample_interval=500 loop.max_part=7 bootconfig buildvariant=userdebug console=hvc0 panic=-1 earlycon=uart8250,io,0x3f8 pci=noacpi reboot=k audit=1
```

### CODE REVIEW

**Comment by adminMMT29B** [comment]
Duplicate of #

**Comment by Aungmyatthuu** [comment]
> https://android-review.googlesource.com/c/platform/system/core/+/1615298
> 
> /proc/bootconfig
> ```
> hardware = "cutf_cvm"
> kernel.mac80211_hwsim.radios = "0"
> kernel.snd-hda-intel.enable = "0"
> kernel.vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size = "16384"
> androidboot.fstab_suffix = "f2fs"
> androidboot.slot_suffix = "_a"
> androidboot.force_normal_boot = "1"
> androidboot.console = "invalid"
> androidboot.boot_devices = "pci0000:00/0000:00:08.0", "pci0000:00/0000:00:09.0"
> androidboot.cpuvulkan.version = "4198400"
> androidboot.hardware.gralloc = "minigbm"
> androidboot.hardware.hwcomposer = "ranchu"
> androidboot.hardware.egl = "angle"
> androidboot.hardware.vulkan = "pastel"
> androidboot.serialno = "CFCVD10D9362DF54"
> androidboot.lcd_density = "320"
> androidboot.setupwizard_mode = "DISABLED"
> androidboot.vsock_tombstone_port = "6600"
> androidboot.cuttlefish_config_server_port = "6800"
> androidboot.vendor.vehiclehal.server.cid = "2"
> androidboot.vendor.vehiclehal.server.port = "9210"
> androidboot.vendor.audiocontrol.server.cid = "3"
> androidboot.vendor.audiocontrol.server.port = "9410"
> androidboot.vsock_frames_port = "6900"
> androidboot.modem_simulator_ports = "9200"
> androidboot.wifi_mac_address = "40:1:2:3:4:1"
> androidboot.verifiedbootstate = "orange"
> ```
> /proc/cmdline
> ```
> mac80211_hwsim.radios="0" snd-hda-intel.enable="0" vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size="16384" stack_depot_disable=on  printk.devkmsg=on firmware_class.path=/vendor/etc/ init=/init kfence.sample_interval=500 loop.max_part=7 bootconfig buildvariant=userdebug console=hvc0 panic=-1 earlycon=uart8250,io,0x3f8 pci=noacpi reboot=k audit=1
> ```

**Comment by iRONxDROID-9-PIe** [comment]
Sweet,                             Thanks...                                               --       Sent from       Canary                                                            On Wednesday, Jun 16, 2021 at 6:28 PM, Aungmyatthuu <       ***@***.***> wrote:                                         https://android-review.googlesource.com/c/platform/system/core/ /1615298        /proc/bootconfig        hardware = "cutf_cvm"kernel.mac80211_hwsim.radios = "0"kernel.snd-hda-intel.enable = "0"kernel.vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size = "16384"androidboot.fstab_suffix = "f2fs"androidboot.slot_suffix = "_a"androidboot.force_normal_boot = "1"androidboot.console = "invalid"androidboot.boot_devices = "pci0000:00/0000:00:08.0", "pci0000:00/0000:00:09.0"androidboot.cpuvulkan.version = "4198400"androidboot.hardware.gralloc = "minigbm"androidboot.hardware.hwcomposer = "ranchu"androidboot.hardware.egl = "angle"androidboot.hardware.vulkan = "pastel"androidboot.serialno = "CFCVD10D9362DF54"androidboot.lcd_density = "320"androidboot.setupwizard_mode = "DISABLED"androidboot.vsock_tombstone_port = "6600"androidboot.cuttlefish_config_server_port = "6800"androidboot.vendor.vehiclehal.server.cid = "2"androidboot.vendor.vehiclehal.server.port = "9210"androidboot.vendor.audiocontrol.server.cid = "3"androidboot.vendor.audiocontrol.server.port = "9410"androidboot.vsock_frames_port = "6900"androidboot.modem_simulator_ports = "9200"androidboot.wifi_mac_address = "40:1:2:3:4:1"androidboot.verifiedbootstate = "orange"        /proc/cmdline        mac80211_hwsim.radios="0" snd-hda-intel.enable="0" vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size="16384" stack_depot_disable=on  printk.devkmsg=on firmware_class.path=/vendor/etc/ init=/init kfence.sample_interval=500 loop.max_part=7 bootconfig buildvariant=userdebug console=hvc0 panic=-1 earlycon=uart8250,io,0x3f8 pci=noacpi reboot=k audit=1              —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.       ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/topjohnwu/Magisk/pull/4384#issuecomment-862797410","url": "https://github.com/topjohnwu/Magisk/pull/4384#issuecomment-862797410","name": "View Pull Request"},"description": "View this Pull Request on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Review by lokoloko13 — APPROVED** [review]

**Comment by tulza121** [comment]
> https://android-review.googlesource.com/c/platform/system/core/+/1615298
> 
> /proc/bootconfig
> 
> ```
> hardware = "cutf_cvm"
> kernel.mac80211_hwsim.radios = "0"
> kernel.snd-hda-intel.enable = "0"
> kernel.vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size = "16384"
> androidboot.fstab_suffix = "f2fs"
> androidboot.slot_suffix = "_a"
> androidboot.force_normal_boot = "1"
> androidboot.console = "invalid"
> androidboot.boot_devices = "pci0000:00/0000:00:08.0", "pci0000:00/0000:00:09.0"
> androidboot.cpuvulkan.version = "4198400"
> androidboot.hardware.gralloc = "minigbm"
> androidboot.hardware.hwcomposer = "ranchu"
> androidboot.hardware.egl = "angle"
> androidboot.hardware.vulkan = "pastel"
> androidboot.serialno = "CFCVD10D9362DF54"
> androidboot.lcd_density = "320"
> androidboot.setupwizard_mode = "DISABLED"
> androidboot.vsock_tombstone_port = "6600"
> androidboot.cuttlefish_config_server_port = "6800"
> androidboot.vendor.vehiclehal.server.cid = "2"
> androidboot.vendor.vehiclehal.server.port = "9210"
> androidboot.vendor.audiocontrol.server.cid = "3"
> androidboot.vendor.audiocontrol.server.port = "9410"
> androidboot.vsock_frames_port = "6900"
> androidboot.modem_simulator_ports = "9200"
> androidboot.wifi_mac_address = "40:1:2:3:4:1"
> androidboot.verifiedbootstate = "orange"
> ```
> 
> /proc/cmdline
> 
> ```
> mac80211_hwsim.radios="0" snd-hda-intel.enable="0" vmw_vsock_virtio_transport_common.virtio_transport_max_vsock_pkt_buf_size="16384" stack_depot_disable=on  printk.devkmsg=on firmware_class.path=/vendor/etc/ init=/init kfence.sample_interval=500 loop.max_part=7 bootconfig buildvariant=userdebug console=hvc0 panic=-1 earlycon=uart8250,io,0x3f8 pci=noacpi reboot=k audit=1
> ```

#4455

**Comment by DavisNT** [comment]
This (the commit [fb4eb72](https://github.com/topjohnwu/Magisk/pull/4384/commits/fb4eb7249b648d69bff7e0a969feca25b3141ac1)) should resolve #4547

**Comment by canyie** [comment]
Replaced by #4596 #4597 #4598 #4599 #4600 #4601

**Comment by DavisNT** [comment]
@vvb2060, @canyie Looks like [fb4eb72](https://github.com/topjohnwu/Magisk/commit/fb4eb7249b648d69bff7e0a969feca25b3141ac1) that is a fix for #4547 was not merged. I don't see an open PR for it either.

**Pull request closed without merging**
