### PR TITLE
Change colors

### PR DESCRIPTION
**Pull request by RikkaW**
Mew: The original color looks like disabled colors.
Zapdos: The original colors have extremely poor readability. For yellow colors, it is difficult to balance readability and beauty, maybe remove it is a better choice?

### CODE REVIEW

**Comment by diareuse** [comment]
@RikkaW You can actually experiment with different colors for light and dark themes, it doesn't have to be universally defined for both themes.

I'd suggest making the Mew colors more vibrant or lighter for dark theme and Zapdos' colors making somewhat orange-y for light theme to improve legibility. I really like how the yellow colors look on the dark background, removing it would be a waste.

Splitting the themes could be effectively achieved like this:

File `values/themes_md2.xml`:

```xml
<style name="ThemeFoundationMD2.Zapdos.Base" parent="ThemeFoundationMD2.Piplup">
    <item name="colorSecondary">#B29667</item>
    <item name="colorSecondaryVariant">#80B29667</item>
    <item name="colorOnPrimary">#000000</item>
    <item name="colorOnPrimaryVariant">#D9222222</item>
</style>

<style name="ThemeFoundationMD2.Zapdos" parent="ThemeFoundationMD2.Zapdos.Base">
    <item name="colorPrimary">#F3BC16</item>
    <item name="colorPrimaryVariant">#80F3BC16</item>
</style>
```

File `values-night/themes_md2.xml`:

```xml
<style name="ThemeFoundationMD2.Zapdos" parent="ThemeFoundationMD2.Zapdos.Base">
    <item name="colorPrimary">#FBD179</item>
    <item name="colorPrimaryVariant">#80FBD179</item>
</style>
```

---

These colors are just an example I was trying out. Just make sure the Zapdos theme doesn't come out brown in the end. Thanks for this contribution!

**Comment by RikkaW** [comment]
@diareuse Forgive me for forgetting about the dark theme, my changes supposed to for light themes only. Zapdos does look great under the dark theme, I admit it would be a waste to remove it.

My initial goal for the light theme is to let Mew has a lower lightness (and maybe a little higher saturation) color and Zapdos has a lower lightness and lower saturation color.

**Comment by diareuse** [comment]
Haha, no worries 🙂 You can just update the PR with the changes described above, once you're ready ping me again to review the changes 👍

**Comment by RikkaW** [comment]
@diareuse I finished the changes please review them.

And one more question: Is making `colorSecondary` a litter lighter under the dark theme (especially for Piplup, Rayquaza, Zapdos) a good idea?

**Review by diareuse — APPROVED** [review]
@topjohnwu this can be merged

**Pull request merged**
