### PR TITLE
Fix copy sepolicy rules when install module

### LINKED ISSUE #4248: After installing the module and restarting, Magisk will not load SEPolicy rules
**Device Information**
- Device: Xiaomi Note 3
- Android version: 9.0
- Magisk version name: f49966d8
- Magisk version code: 22103

**Describe the bug**
After installing the [LSPosed module](https://github.com/LSPosed/LSPosed/releases),restart the device. The module shows that SEPolicy is not loaded correctly. At this time, Magisk must be reinstalled before SEPolicy can be loaded normally.

[boot.zip](https://github.com/topjohnwu/Magisk/files/6330581/boot.zip)
[logcat.zip](https://github.com/topjohnwu/Magisk/files/6330582/logcat.zip)
[magisk_log_2021-04-18T13-57-08Z.zip](https://github.com/topjohnwu/Magisk/files/6330583/magisk_log_2021-04-18T13-57-08Z.zip)

### PR DESCRIPTION
**Pull request by vvb2060**
Fix #4248

### CODE REVIEW

**Review by yujincheng08 — APPROVED** [review]

**Comment by androiddisk** [comment]
请问什么情况条件为真 "${RULESDIR:0:1}" != "/" 

有一种情况，如果$(magisk --path)/.magisk/mirror/sepolicy.rules真实的文件夹不存在。那么创建文件夹的命令会报错mkdir -p $RULESDIR/$MODNAME


What condition is true "${rulesdir: 0:1}"! = / "
In one case, if $(magick -- path) /. Magick / mirror / sepolicy.rules, the real folder does not exist. Then the command to create a folder will report an error mkdir -p $rulesdir/$modname

gauguinpro:/ $ su
gauguinpro:/ # ls -l $(magisk --path)/.magisk/mirror/sepolicy.rules
lrwxrwxrwx 1 root root 33 1970-01-25 05:54 /sbin/.magisk/mirror/sepolicy.rules -> /sbin/.mianju/mirror/cache/magisk
gauguinpro:/ # rm -fr /sbin/.mianju/mirror/cache/magisk
gauguinpro:/ #
gauguinpro:/ # mkdir -p /sbin/.magisk/mirror/sepolicy.rules/demo
mkdir: '/sbin/.magisk/mirror/sepolicy.rules/demo': No such file or directory
1|gauguinpro:/ #

**Comment by androiddisk** [comment]
RULESDIR=$(readlink $active_dir)
    [ "${RULESDIR:0:1}" != "/" ] && RULESDIR="$(magisk --path)/.magisk/mirror/$RULESDIR"

Change to



    RULESDIR=$(readlink $active_dir)
    [ "${RULESDIR:0:1}" != "/" ] && RULESDIR=$(readlink -f $active_dir)

is ok？

**Comment by yujincheng08** [comment]
> ```
> RULESDIR=$(readlink $active_dir)
> [ "${RULESDIR:0:1}" != "/" ] && RULESDIR="$(magisk --path)/.magisk/mirror/$RULESDIR"
> ```
> 
> Change to
> 
> ```
> RULESDIR=$(readlink $active_dir)
> [ "${RULESDIR:0:1}" != "/" ] && RULESDIR=$(readlink -f $active_dir)
> ```
> 
> is ok？

no. see #4104

**Comment by androiddisk** [comment]
> > ```
> > RULESDIR=$(readlink $active_dir)
> > [ "${RULESDIR:0:1}" != "/" ] && RULESDIR="$(magisk --path)/.magisk/mirror/$RULESDIR"
> > ```
> > 
> > 
> > Change to
> > ```
> > RULESDIR=$(readlink $active_dir)
> > [ "${RULESDIR:0:1}" != "/" ] && RULESDIR=$(readlink -f $active_dir)
> > ```
> > 
> > 
> > is ok？
> 
> no. see #4104

but can't mkdir $(magisk --path)/.magisk/mirror/$RULESDIR

**Review by aviraxp — APPROVED** [review]

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
