### PR TITLE
Added safetynet shortcut

### LINKED ISSUE #2634: [Feature Request] App Shortcut for safety net check
It'd be really nice to have an app shortcut (long press app icon) for magisk manager that jumps right into the integrated safety net check, as I frequently use it, e.g. before using google pay.

### PR DESCRIPTION
**Pull request by diareuse**
DID NOT TEST this addition due to lack of time atm.
Test it yourself or wait for confirmation.

Fixes #2634

### CODE REVIEW

**Comment by diareuse** [comment]
Ready for review.

**Comment by Anitaislam** [comment]
Diff

**Comment by osm0sis** [comment]
This needs a rebase now I guess, @diareuse. :slightly_smiling_face:

**Comment by osm0sis** [comment]
I guess this is dead?

**Comment by topjohnwu** [comment]
@osm0sis I'm keeping this code around. I would consider adding it back to the app once I made up my mind (it will not be in the default app icon list like it was implemented in this PR)

**Comment by osm0sis** [comment]
Sounds good, I'll close the associated Issue however. :+1:

**Review by lalo-cmd — CHANGES_REQUESTED** [review]
feature/safetynet-shortcut

**Pull request closed without merging**
