### PR TITLE
Delete invalid deny list

### PR DESCRIPTION
**Pull request by rawer886**
If app reduces some processes after updated, then these processes cannot be removed from the denylist

### CODE REVIEW

**Comment by vvb2060** [comment]
I think invalid processes should only be deleted when the user updates the deny state of the app

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/6e299018a432deae49df454a9e5b5a2f9d57b9ce/native/src/zygisk/deny/utils.cpp#L287-L295

You can delete the process name parameter when it is not expanded.

**Comment by rawer886** [comment]
> https://github.com/topjohnwu/Magisk/blob/6e299018a432deae49df454a9e5b5a2f9d57b9ce/native/src/zygisk/deny/utils.cpp#L287-L295
> 
> You can delete the process name parameter when list is not expanded.

The above code provide the ability to delete all processes. 
But in magisk app, you can only delete all the **current processes** of the application. If you want to delete the processes that existed before, you must execute "magisk --denylist rm [packagename]" in cli.

**Comment by rawer886** [comment]
https://github.com/topjohnwu/Magisk/blob/928a16d8cc4b93bd10cd0568a9661591d623c79e/app/src/main/java/com/topjohnwu/magisk/ui/deny/AppProcessInfo.kt#L90-L95

@vvb2060 

E.g:  There are two records in denylist
```
com.xxx.demo|com.xxx.demo
com.xxx.demo|com.xxx.demo:abc
```
The `com.xxx.demo:abc` process is deleted after Demo upgrade. When I want to remove the Demo App from Denylist, I can only remove the process `com.xxx.demo|com.xxx.demo`, but `com.xxx.demo|com.xxx.demo:abc` cannot be operated.

**Comment by yujincheng08** [comment]
afaik, this is expected

**Pull request closed without merging**
