### PR TITLE
Add info about android 11 recovery entering

### PR DESCRIPTION
**Pull request by nettnikl**
This took me a good time to understand, so this info might help anyone who tries to flash an updated magisk to an old device.

### CODE REVIEW

**Comment by nin0-dev** [comment]
You wrote "Magsik", but it's "Magisk". (Line 79)

**Comment by vvb2060** [comment]
I don't understand what you mean…

**Comment by nettnikl** [comment]
> You wrote "Magsik", but it's "Magisk". (Line 79)

Thanks for spotting!

**Comment by nettnikl** [comment]
> I don't understand what you mean…

Hm, maybe i have to clarify more then. If you flash Android 11 or later, you cannot enter recovery mode without connecting the phone to a pc. So, to enter magisk, you have to do that, if you installed magisk as recovery.

**Comment by vvb2060** [comment]
Can you explain why? What was done on the phone and why it didn't work, and what needs to be done on the PC.

**Comment by nettnikl** [comment]
No, i cannot - this is a change in android, and i'm not a google engineer, so i don't understand their reason as well.
You don't have to do anything on PC, it's literally just connecting a power source to your phone, waiting for the charge symbol, then proceeding with starting your phone into recovery. You can test by yourself with a rooted Galaxy S10 (as you have to install Magisk to recovery here), if you have one at disposal.

**Comment by vvb2060** [comment]
What did you do on the phone to try to reboot to recovery and what was the result.

**Comment by nettnikl** [comment]
The "old" way also works on older Android versions, just not in 11 (or so i read) and above (i tested, and can confirm for 12).

**Comment by nettnikl** [comment]
As a summary, after installing Magisk in recovery (starting from power off):

(Recovery Key Combo) → (Splash screen) → (Release all buttons) → (System with Magisk)

Does not work if the base system is based on Android 12.

The fix is described in my commit. The same info can be found all over the internet.

**Comment by vvb2060** [comment]
what was the result？

without PC
(Recovery Key Combo) → (Splash screen) → (Release all buttons) → ???

without PC
(Recovery Key Combo) → (Splash screen) → (Long press volume up) → ???

connect PC
(Recovery Key Combo) → (Splash screen) → (Release all buttons) → ???

connect PC
(Recovery Key Combo) → (Splash screen) → (Long press volume up) → ???


Recovery Mode? 
Or System with Magisk? 
Or System with NO Magisk?

**Comment by nettnikl** [comment]
With Android 11 or later:

without PC
(Recovery Key Combo) → (Splash screen) → (Release all buttons) → System with NO Magisk

without PC
(Recovery Key Combo) → (Splash screen) → (Long press volume up) → System with NO Magisk

connect PC
(Recovery Key Combo) → (Splash screen) → (Release all buttons) → System with Magisk

connect PC
(Recovery Key Combo) → (Splash screen) → (Long press volume up) → Recovery Mode

I can repeat the cases once again, when I'm back at my computer.

**Comment by vvb2060** [comment]
Thanks for the explanation, it looks like the issue is related to #4624.

**Comment by nettnikl** [comment]
Might be, i cannot test, as i don't own this device - but isn't this about a Android 10 phone?

**Comment by vvb2060** [comment]
Maybe we should compare the kernel version instead of the Android version.

**Comment by nettnikl** [comment]
Oh, yeah, sounds reasonable. I thought it is caused by Android 11, because i read that online. Let's verify.

Mine is 4.14.113-23727351

**Comment by pndwal** [comment]
> Thanks for the explanation, it looks like the issue is related to #4624.

I don't think so... That issue is about Magisk Daemon failing to detect safe mode key combo presses due to timing inconsistencies...

This PR is simply to alert users to Samsung's new key combo requirement that usb is connected (even a headset apparently) for devices (seems may affect Exynos socs only) running One UI 3+ / Android 11+ for recovery and download modes.
https://www.naldotech.com/how-to-boot-into-recovery-mode-on-samsung-one-ui-3-0-new-method/

I'm guessing this was done to avoid accidental booting to special modes...

As key combos vary between devices, and even between Samsung models (eg. some use Bixby key while others don't have it ...), I'm not sure Magisk needs to make users aware of device specific requirements for entering special modes...

**Comment by nettnikl** [comment]
Well, in this case, it is actually the example case, which does not work as described, which was very confusing for me (Samsung S10 is the example device mentioned here). Especially as it is already exeptional to have magisk installed on recocery nowadays (so there are not many devices this does not apply too which are installed on recovery at the same time).

At the very least, we might want to suggest that there are differences between Android versions, and change the example device mentioned - the way it currently stands, the example seems incorrect.

**Comment by topjohnwu** [comment]
How to reboot into recovery varies device to device. Not all devices running Android 11+ requires connecting to a PC to reboot to recovery, and the guide should not specify any device specific stuffs.

**Comment by nettnikl** [comment]
Then please remove Samsung Galaxy S10 as example. As mentioned, this example is now plainly wrong for all recent Android version.

**Pull request closed without merging**
