### PR TITLE
Fix Magisk detection by parsing ro.bootmode

### PR DESCRIPTION
**Pull request by fox8091**
This prevents apps from detecting Magisk when Magisk is installed to the recovery partition. In this configuration, ro.bootmode is set to recovery, meanwhile booting normally produces "unknown" in this field.

### CODE REVIEW

**Comment by fox8091** [comment]
I should note, this primarily applies to Samsung and EMUI 9 devices, though it applies to any device that lacks a ramdisk for the boot partition.

**Comment by sudoxd** [comment]
xd

**Comment by fox8091** [comment]
On my Pixel 2 it shows as "unknown" by default, but I can test if "normal" works as well.

**Comment by osm0sis** [comment]
@fox8091, and did "normal" work? Logically "normal" seems like it would be the more correct, standard value across devices. :wink:

Please amend your pull request commit with normal instead of unknown if it doesn't cause any issues on your Pixel.

**Comment by osm0sis** [comment]
@fox8091 any follow-up?

**Pull request closed without merging**
