### PR TITLE
Update french translations

### LINKED ISSUE #4210: In order to fix FR translations : What is the difference between "OS apps" and "System apps" ?
Device: Any
Android version: Any
Magisk version name: 22.1
Magisk version code: 22102

Both [this translation](https://github.com/topjohnwu/Magisk/blob/c4e8dda37cd932049dbf637f47a150ecd08705f0/app/src/main/res/values-fr/strings.xml#L101) and [this one](https://github.com/topjohnwu/Magisk/blob/c4e8dda37cd932049dbf637f47a150ecd08705f0/app/src/main/res/values-fr/strings.xml#L102) mean *Show System apps*.

The only difference between them is that the first one would translate to "System applications" whereas the second one would be "System apps". 

So apart from the way the word application is written, there is no clear difference here between OS apps and System apps.

So how do you differentiate OS apps from System apps

### PR DESCRIPTION
**Pull request by cl-ement05**
Especially to fix #4210 and more

### CODE REVIEW

**Comment by cl-ement05** [comment]
I just don't understand why check are not passing (build app fails). I only changed an xml file with strings

**Comment by androidacy** [comment]
```
/home/runner/work/Magisk/Magisk/app/src/main/res/values-fr/strings.xml:242:5-101: AAPT: error: unescaped apostrophe in string
```

**Comment by androidacy** [comment]
You need to escape `\` things like '  and "

**Comment by osm0sis** [comment]
Why are you changing English values when you say you're updating the French translation?

**Comment by cl-ement05** [comment]
> Why are you changing English values when you say you're updating the French translation?
> 
> Edit: Haha never mind, Google Translate was pretty seamless and even changed fr to en in the path 😅

Lol I don't understand. Where did I change english values ??

**Comment by cl-ement05** [comment]
> You need to escape `\` things like '  and "

Oh my bad yes I totally forgot to escape commas

**Comment by cl-ement05** [comment]
> 
> 
> You need to escape `\` things like ' and "

The strange thing here is that some comas are not escaped in this file (see [this example](https://github.com/cl-ement05/Magisk/blob/291a2f84efc9ad539022b7be683f61b8df89819f/app/src/main/res/values-fr/strings.xml#L54)). However, build succeeds but how ?

**Comment by topjohnwu** [comment]
@cl-ement05 those are Unicode quotes, not the same a the ASCII quotes 😉

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
