### PR TITLE
manager.sh: check vbmeta device by getprop

### PR DESCRIPTION
**Pull request by vvb2060**
https://cs.android.com/android/platform/superproject/main/+/main:external/avb/libavb/avb_cmdline.c;l=223-233;drc=45ec542fae38b7a938774033ab85fb128edbab9f

### CODE REVIEW

**Review by topjohnwu — APPROVED** [review]

**Comment by osm0sis** [comment]
How about checking ro.product.ab_ota_partitions for vbmeta? Still prop-based.

**Comment by osm0sis** [comment]
> > getprop | grep vbmeta
> 
> This is on my A11 stock rom:
> 
> ```
> Infinix-X695C:/ $ getprop | grep vbmeta
> [ro.boot.vbmeta.device_state]: [locked]
> [vendor.boot.vbmeta.device_state]: [locked]
> Infinix-X695C:/ $ su
> Infinix-X695C:/ # getprop | grep vbmeta
> [ro.boot.vbmeta.device_state]: [locked]
> [vendor.boot.vbmeta.device_state]: [locked]
> Infinix-X695C:/ #
> ```
> 
> Tried this too:
> 
> ```
> Infinix-X695C:/ $ getprop ro.product.ab_ota_partitions | grep -wq vbmeta
> 1|Infinix-X695C:/ $
> ```
> 
> No vbmeta traces

Hmm, well what's there now, and what will be added with my PR is still better than the broken path check from before.

**Comment by osm0sis** [comment]
@Stillhard your device definitely has a vbmeta partition? Is it an A/B device or A-only? Can you provide a full unrooted getprop output for your device?

See here: https://github.com/topjohnwu/Magisk/pull/7220#issuecomment-1670570045

**Comment by osm0sis** [comment]
I wonder if first_api_level could be useful to us here. 🤔

**Pull request merged**
