### PR TITLE
Rename docs/changes.md to docs/#!/sbin/sh echo "hello world !, using …

### PR DESCRIPTION
**Pull request by Liamtoha**
…echo" ui_print "run script, using ui_print 2"

#!/sbin/sh echo "hello world !, using echo" ui_print "run script, using ui_print 2"

### CODE REVIEW

**Comment by Liamtoha** [comment]
Approved

**Comment by Liamtoha** [comment]
Merge approved

**Comment by Liamtoha** [comment]
…echo" ui_print "run script, using ui_print 2"

#!/sbin/sh echo "hello world !, using echo" ui_print "run script, using ui_print 2"

**Comment by Liamtoha** [comment]
…echo" ui_print "run script, using ui_print 2"

#!/sbin/sh echo "hello world !, using echo" ui_print "run script, using ui_print 2"

Merge approved

**Comment by Liamtoha** [comment]
gh pr checkout 6940

**Comment by tinnus1988** [comment]
ในวันที่ พฤ. 27 เม.ย. 2023 07:00 น. Liamtoha ***@***.***>
เขียนว่า:

**Pull request closed without merging**
