### PR TITLE
Revert "Hide OTA option on virtual A/B devices"

### PR DESCRIPTION
**Pull request by aviraxp**
* Does not work because of SELinux, and installation on virtual
   A/B devices work just fine.

This reverts commit 00659e4795dd985b0bbb1b630d089116b9da9e9c.

### CODE REVIEW

**Comment by osm0sis** [comment]
It does not work on any Virtual A/B device that uses Google Play services mediated Incremental OTAs, which is at least Pixels, OnePlus 8T and newer in North America, and probably others.

You're correct that the option hiding is broken however, since it still shows on my 8T erroneously.

See: https://github.com/topjohnwu/Magisk/issues/3963

**Comment by aviraxp** [comment]
Can you provide more information about Google Play services mediated Incremental OTAs? I am using OP8T and it works with the default updater.

**Comment by osm0sis** [comment]
It works for you because you're presumably not using the North American variant? Here's the lengths I've worked out that needed to be gone through to retain SafetyNet/Certified passing and not bricking it post-OTA: https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/page-149#post-84764713

**Comment by osm0sis** [comment]
And a bit more supplemental info here: https://twitter.com/osm0sis_xda/status/1378019206466314244

**Comment by ameaninglessname** [comment]
Would this commit be merged soon?

**Comment by osm0sis** [comment]
It's not really sufficient. The logic is overall still broken even with this revert.

**Comment by osm0sis** [comment]
I think just whatever effect SELinux has on it needs to be fixed. Someone reported it only showed when SELinux was enforcing for some reason. 🤔

**Review by osm0sis — APPROVED** [review]

**Comment by osm0sis** [comment]
Don't think this has been resolved yet, no?

**Comment by aviraxp** [comment]
Nope, but I am thinking of other mechanisms, such as a warning dialog.

**Comment by aviraxp** [comment]
This commit does not have any issues at all.

@osm0sis the issue lies in install instruction. You need to either turn on 'Auto update after reboot' in dev options or reboot with Google play update dialog. Without this, update engine won't do dm-verity related work and cause bootloop.

**Pull request closed without merging**
