### PR TITLE
Add Travis build (WIP)

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

@topjohnwu What versionString/versionCode needs to be? Or maybe a different build target? Thanks

https://travis-ci.org/gliptak/Magisk/builds/332613276

```
$ python3.6 build.py all
usage: build.py all [-h] versionString versionCode
build.py all: error: the following arguments are required: versionString, versionCode
```

### CODE REVIEW

**Comment by TheComputerGuy96** [comment]
@gliptak Hi

You can take a look at [this repository](https://github.com/TheComputerGuy96/Magisk/tree/travisci-dev) for some info

**Comment by 0o0TheDude0o0** [comment]
@gliptak build.py all 15.12345 01242018
It's arbitrary for your own builds. You can make the build version and versioncode whatever you like.

**Comment by gliptak** [comment]
Signing step failed, probably need to be removed from the target (unless keys are added to Travis?)

https://travis-ci.org/gliptak/Magisk/builds/332920054

```
* Signing / Adjusting Zip
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
7838621 bytes
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at com.topjohnwu.crypto.JarMap.<init>(JarMap.java:41)
	at com.topjohnwu.crypto.JarMap.<init>(JarMap.java:37)
	at com.topjohnwu.crypto.ZipSigner.main(ZipSigner.java:37)
Second sign flashable zip failed!
```

**Comment by gliptak** [comment]
@TheComputerGuy96 Thanks for the pointer. Is there a reason why your Travis setup didn't make it into ```topjohnwu```'s repo?

**Comment by 0o0TheDude0o0** [comment]
@gliptak correct. Or just sign with test keys.

**Comment by gliptak** [comment]
@0o0TheDude0o0 What would better build targets to use? Or would you point me to some snippets on signing I could use (or Travis configuration examples perhaps)? Thanks

**Comment by TheComputerGuy96** [comment]
@gliptak Because I thought that my build script is not too great to make a PR about

**Comment by 0o0TheDude0o0** [comment]
@gliptak Man I will have to look at this tomorrow. Today was my sons birthday and I was busy with that. I have not compiled this since 15.1 or .2 specifically for the Pixel 2 XL sdk 24 because I have not had to. There were dtbo patching issues so I had to modify the code and compile it with the fixes. Since then they have been fixed and I just run official builds now :) But tomorrow I will sync the repos and compile it. I will post up the output for you and maybe that will help you out.

**Comment by gliptak** [comment]
@0o0TheDude0o0 Thank you

**Comment by gliptak** [comment]
@topjohnwu Are you interested in this PR? Thanks

**Pull request closed without merging**
