### PR TITLE
Update install.mdg

### PR DESCRIPTION
**Pull request by MDGSTL1985**
hope you like it

### CODE REVIEW

**Comment by Didgeridoohan** [comment]
None of that makes any sense...

**Comment by julian-fairfax** [comment]
Summary of changes:
- Changed font weight on some pieces of test from bold to normal
- Broke some hyperlinks
- Somehow managed to put an xml file in the readme...

Why did you do this?

**Review by julian-fairfax — CHANGES_REQUESTED** [review]
Summary of changes:
- Changed font weight on some pieces of text from bold to normal
- Broke some hyperlinks
- Somehow managed to put an xml file in the readme...

This pull request should be closed.

**Comment by osm0sis** [comment]
Trash ass bots. 🙄

**Pull request closed without merging**
