### PR TITLE
Add Swahili translation

### PR DESCRIPTION
**Pull request by AngelofVerdant**
:x: Added strings.xml files  to `app/src/main/res/values-sw/`  and `stub/src/main/res/values-sw/` folders to add support for Swahili in the future which I am currently in the process of translating

### CODE REVIEW

**Comment by yujincheng08** [comment]
> /home/runner/work/Magisk/Magisk/app/src/main/res/values-sw/strings.xml:180: Error: "user_indepenent_summary" is translated here but not found in default locale [ExtraTranslation]
> 
>     <string name="user_indepenent_summary">Each user has their own separate root rules</string>

**Comment by AngelofVerdant** [comment]
Whooooah , okay

**Comment by AngelofVerdant** [comment]
@yujincheng08    Issue has been fixed

**Comment by AngelofVerdant** [comment]
@yujincheng08 , you there?

**Pull request closed without merging**
