### PR TITLE
master

### PR DESCRIPTION
**Pull request by LaudateCorpus1**

### CODE REVIEW

**Comment by osm0sis** [comment]
Looks like more bots generating bullshit contribution history.. 🙄

**Comment by LaudateCorpus1** [comment]
Ouch, if you dig there is actually some stuff from me here! Mainly pre-approved and payed for bot-source-code merges for security purposes. Almost like you guys forgot that Ubuntu has a new stable version out that has some security updates, you know? (e.g. Whitesource config, and the yml)

**Comment by osm0sis** [comment]
@vvb2060 @topjohnwu, any truth to that? If this guy isn't a bot I don't see why they're such a mess and/or how these changes are useful for Magisk.

**Comment by osm0sis** [comment]
Yeah that pointless ImgBot and random merge commits are what seemed like the biggest red flags for being contribution spam. Confusing when they semi-coherently talk back at you though. 😝

**Pull request closed without merging**
