### PR TITLE
Fixes

### LINKED ISSUE #4: problems with module containing system/bin and lib64
I'm trying to create a module to install openssh and rsync binaries, this did work in Magisk v6.

the module files are:

```
system/bin/sshd
system/bin/ssh
system/lib64/libssh.so
system/xbin/rsync
system/placeholder
```

When the `lib64/libssh.so` file is included, the device bootloops. It appears that during the dummy mount the real contents of lib64 get lost briefly and it never recovers

```
--------- beginning of crash
01-09 13:42:36.943  5283  5283 F libc    : CANNOT LINK EXECUTABLE "log": file offset for the library "libcutils.so" >= file size: 0 >= 0
01-09 13:42:36.943  5283  5283 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5283 (log)
01-09 13:42:36.964  5286  5286 F libc    : CANNOT LINK EXECUTABLE "log": file offset for the library "libcutils.so" >= file size: 0 >= 0
01-09 13:42:36.964  5286  5286 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5286 (log)
01-09 13:42:36.974  5288  5288 F libc    : CANNOT LINK EXECUTABLE "log": file offset for the library "libcutils.so" >= file size: 0 >= 0
01-09 13:42:36.974  5288  5288 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5288 (log)
01-09 13:42:36.995  5294  5294 F libc    : CANNOT LINK EXECUTABLE "log": file offset for the library "libcutils.so" >= file size: 0 >= 0
01-09 13:42:36.995  5294  5294 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5294 (log)
```

Trying with just the binaries, I get ssh and sshd in `/system/bin` 

```
1|angler:/ $ ls -l /magisk/.core/dummy/system/bin/ssh*
-rwxr-xr-x 1 root root 182800 2016-10-04 19:59 /magisk/.core/dummy/system/bin/ssh
-rwxr-xr-x 1 root root 245448 2016-10-04 19:59 /magisk/.core/dummy/system/bin/sshd

angler:/ $ ls -l /system/bin/ssh*                   
-rwxr-xr-x 1 root root 182800 2016-10-04 19:59 /system/bin/ssh
-rwxr-xr-x 1 root root 245448 2016-10-04 19:59 /system/bin/sshd
```

but phh's su is no longer available:

```
angler:/ $ echo $PATH
/magisk/.core/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/magisk/.core/busybox:/system/xbin
angler:/ $ ls -l /magisk/.core/bin
ls: /magisk/.core/bin: No such file or directory
```

here's everything in /magisk (except .core)

```
/magisk/00roothelper/supersu.sh
/magisk/00roothelper/supersu.prop
/magisk/00roothelper/post-fs-data.sh
/magisk/00roothelper/phh.sh
/magisk/00roothelper/phh.prop
/magisk/phh/bin/su
/magisk/phh/bin/sepolicy-inject
/magisk/phh/module.prop
/magisk/phh/post-fs-data.sh
/magisk/angler_openssh/system/bin/sshd
/magisk/angler_openssh/system/bin/ssh
/magisk/angler_openssh/system/xbin/rsync
/magisk/angler_openssh/auto_mount
/magisk/angler_openssh/module.prop
/magisk/angler_openssh/service.sh
```

files in .core

```
1|angler:/ $ ls -l /magisk/.core
total 24
drwxr-xr-x 3 root root 4096 1970-01-09 13:19 dummy
-rw-r--r-- 1 root root   56 2009-01-01 08:00 hosts
drwxr-xr-x 3 root root 4096 1970-01-09 13:19 mirror

```

### PR DESCRIPTION
**Pull request by tombriden**
First commit allows dummy binding the lib or lib64 dirs, which partially fixes #4 

Second commit clones /system to full depth, which also fixes lib/lib64 dummy binding as single depth excludes things like /system/lib64/hw which breaks everything

I'm still have the problem of losing the /magisk/.core/bin directory when my openssh module is installed along with phh su though

### CODE REVIEW

**Comment by mbc07** [comment]
How can I test this PR? I have a module which adds a library under /system/lib and /system/lib64 and it also bootloops (like issue #4)...

**Comment by tombriden** [comment]
clone the repo and merge my branch, zip the contents of zip_static and install from recovery like a normal update to magisk. It should boot but may not work properly based on your setup; I still have a problem with it (I think) timing out and not running post-fs scripts which breaks phh root

**Comment by mbc07** [comment]
I tested here and it fixed the issue with /system/lib(64) but phh's SuperUser stopped working. I tried increasing timeouts in init.magisk.rc but sadly it didn't change anything...

**Comment by topjohnwu** [comment]
Sorry for the late reply.
May anyone post a detailed log and the module you are using which causes the crashes?

**Comment by mbc07** [comment]
You can test with [this module] (https://github.com/mbc07/Magisk-Xperia-DRMFix). On official Magisk v8 it'll bootloop, if I fork Magisk and apply this PR, this module works fine and the phone doesn't bootloop, but then phh's SuperUser module won't work (despite being correctly installed and activated).

Regarding the logs, do you need logcat or Magisk logs?

**Comment by tombriden** [comment]
@topjohnwu it looks like its due to timeout or similar in that it never seems to carry on after stage 1 when there are a lot of files being bind mounted so `run_scripts post-fs-data` never executes and that's why phh superuser breaks

**Comment by mbc07** [comment]
@topjohnwu any news? Do you need something else to help debug the problem?

**Comment by topjohnwu** [comment]
Thanks, merged your fixes in f1d3e35aacdaf8bc0e56246129805077f3431b9d

**Pull request closed without merging**
