### PR TITLE
Fix for Meizu devices, better boot image detection

### PR DESCRIPTION
**Pull request by Naboleo**
Added corresponding partition name (bootimg) in search list

### CODE REVIEW

**Comment by dcarb** [comment]
Hi the meizu pro 5 will be work?

**Comment by Naboleo** [comment]
It does with pro5

**Comment by dcarb** [comment]
But what bootimage i need to select? Thanks

**Comment by dcarb** [comment]
Normally i need to select the SDA26 but it doesn't work and i can't upgrade. I'm not alone with this problem... :'(

**Comment by Naboleo** [comment]
This fix, is only applying when install is done through recovery (TWRP). You may try to modify the installer by your own with this fix (until owner release an updated version).
The way APK manage the installation is a different subject, and probably needs to be discussed using report mechanism on forum (XDA ?), github isn't the right way

**Comment by dcarb** [comment]
I write on XDA... It told me to write on githud :/

**Comment by dcarb** [comment]
My nickname is domi14fr!

**Comment by dcarb** [comment]
I will try thanks!

**Comment by dcarb** [comment]
Sorry but I have a resurection remix ROM! On 7.1.2. I'm not with flume is. Sorry

**Comment by TheComputerGuy96** [comment]
Magisk build script (build.py) copies util_functions.sh file (and some other ones) to Magisk Manager (in the app/src/main/assets folder)

**Comment by Naboleo** [comment]
Great. This means, fix could somehow be integrated in manager too

**Comment by Naboleo** [comment]
Build the apk... 
Seems partition is correctly detected too !!!

https://mega.nz/#!fUlnTZ6Y!KwIY2i_REvQ9pGsAOesDSaVe1nb7BwjKRCdpnfVSt1Y

**Comment by dcarb** [comment]
Thanks!
I test your all! It detect the partition and I install magisk 14. Flash is done!
But after reboot, the phone doesn't start and it block on meizu logo... :'( I reinstall my room with TWRP!

**Comment by dcarb** [comment]
Thanks for your help!

**Comment by topjohnwu** [comment]
Many thanks, the changes are added here: 9cb1cf756fd43365b413d31b06d9c6a5f2fd1455

**Pull request closed without merging**
