### PR TITLE
Remove magiskhide documentation

### PR DESCRIPTION
**Pull request by usrDottik**
This is a pull to delete the MagiskHide FAQ and the usage of MagiskHide. I don't see them necessary, as MagiskHide will be replaced with DenyList, and it's code has already been deleted.

Edit: Also added DenyList to it 🙃
~~Edit 2: I forgot to add it to the applet part and at the top in which executable it is embedded 😓~~

### CODE REVIEW

**Review by AhAow353 — APPROVED** [review]

**Comment by justkamiii** [comment]
Heya! Just a quick thing, I already made a PR deleting some of this documentation
https://github.com/topjohnwu/Magisk/pull/4656
If you want, you can PR your other changes into my repo, so they are also committed in my PR

**Review by osm0sis — APPROVED** [review]

**Review by osm0sis — APPROVED** [review]

**Comment by osm0sis** [comment]
```
denylist -> magisk
```

This line needs to be removed, since there is no /dev/*/denylist -> /dev/*/magisk symlink like this suggests.

**Comment by usrDottik** [comment]
> ```
> denylist -> magisk
> ```
> 
> This line needs to be removed, since there is no /dev/*/denylist -> /dev/*/magisk symlink like this suggests.

Removed, anything else that needs editing?

**Comment by osm0sis** [comment]
Nope, looks good!

**Review by osm0sis — APPROVED** [review]

**Comment by Pahistan** [comment]
Heryf

**Comment by Pahistan** [comment]
Opne

**Comment by Pahistan** [comment]
#4681

**Comment by Pahistan** [comment]
355731095267788

**Comment by topjohnwu** [comment]
Done

**Pull request closed without merging**
