### PR TITLE
copy/installation  <sepolicy.rule>

### PR DESCRIPTION
**Pull request by CanoBot**
copy/installation<sepolicy.rule>

### CODE REVIEW

**Comment by androidacy** [comment]
Wow this one even has bot in the **name**

@osm0sis will you do the honors? Also have you (if you have access) considered limiting access for bewlt creates ld accounts in repository settings?

**Comment by osm0sis** [comment]
No access to limit, @topjohnwu will have to look into that.

**Comment by osm0sis** [comment]
Bot. In the name, though. They're not even trying. 🤦‍♂️

**Comment by androidacy** [comment]
It's honestly depressing how much spam or completely worthless issues and PRs I've been seeing on GitHub, and especially this repository. Even githubs own repos are getting hit.

**Comment by osm0sis** [comment]
Anytime they make more than one nonsense PR I report them. 🤷‍♂️

**Comment by androidacy** [comment]
Same. Hope GitHub can do something to stop these sort of things, it's really annoying

**Pull request closed without merging**
