### PR TITLE
Retain PREINITDEVICE in recovery flash if previously found during booted patching

### PR DESCRIPTION
**Pull request by osm0sis**
Should make for fewer cases where the extra reflash step is needed 🙂

### CODE REVIEW

**Comment by vvb2060** [comment]
`magiskboot cpio file sha1` -> `magiskboot cpio file config SHA1`
so, we can use `magiskboot cpio file config PREINITDEVICE`

**Comment by osm0sis** [comment]
Is that an undocumented feature? I only see `magiskboot cpio <file> sha1` and I thought about adapting that for a `preinit` option, but it seemed silly to add 25 lines of code where a simple one-liner in shell would suffice.

**Comment by osm0sis** [comment]
Anything I'm missing @vvb2060 , @topjohnwu ?

**Comment by topjohnwu** [comment]
@osm0sis thanks for you change, I'm removing the ability to extract vars with `magiskboot` and move the logic to shell scripts instead :)

**Pull request closed without merging**
