### PR TITLE
add Albanian translations

### PR DESCRIPTION
**Pull request by cocka11**

### CODE REVIEW

**Review by topjohnwu — CHANGES_REQUESTED** [review]
Please place the xml file in the correct location with the correct file name

**Comment by osm0sis** [comment]
#3505 seems to be the latest.

**Comment by cocka11** [comment]
Sir did you accept the request to add the Albanian language to magisk.

**Comment by osm0sis** [comment]
You opened 3 PRs. I closed all but the most recent, which is linked.

**Comment by cocka11** [comment]
thanks bro 😍

**Pull request closed without merging**
