### PR TITLE
Mount only necessary mirror directories that will be used magic mount

### PR DESCRIPTION
**Pull request by HuskyDG**
Mount only necessary mirror directories that will be used magic mount. I don't think we should recursively bind mount all partitions to mirror as some are unnecessary?

### CODE REVIEW

**Comment by vvb2060** [comment]
af01a3629652857392f0ecae15d4c2f3d66b0e1d
This is to support overlayfs.  It is mounted atomically on modern devices with only one system call.

**Comment by yujincheng08** [comment]
I think it good. But the implementation seems incorrect.

**Comment by nihal697** [comment]
> I think it good. But the implementation seems incorrect.

what exactly is incorrect ? could you please explain?

**Comment by yujincheng08** [comment]
> what exactly is incorrect ? could you please explain?
1. There are duplicated make private for mirror
2. Most mirror_path is no longer needed, so we dont actually need `mirror_node`
3. Since mirror is not complete, we dont need it anymore and we should umount it.

**Comment by yujincheng08** [comment]
After careful thinking, we no longer need mirror anymore. Will sumbit a new PR instead.

**Pull request closed without merging**
