### PR TITLE
Use gradle to setup emulator

### PR DESCRIPTION
**Pull request by yujincheng08**
Windows users will be happier

### CODE REVIEW

**Comment by osm0sis** [comment]
Hmm builds failed

**Comment by yujincheng08** [comment]
hmm, gradle is hard. it runs getprop everytime...

**Comment by yujincheng08** [comment]
Ok now. But there's a bug of stub codegen because mac's fs is case insensitive.

**Comment by yujincheng08** [comment]
`emulator.sh` will support loading modules' sepolicies if #4642 is merged.

Otherwise we can:
```sh
for file in /data/adb/modules/*/sepolicy.rule; do
  ./magiskpolicy --live --apply $file
done
```
but it will fail if some modules requires sepolicies in `post-fs-data.sh`

**Pull request closed without merging**
