### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Vazkii**
Having an ISSUE_TEMPLATE.md file in the root of your repo will pre-populate the contents of the file to anyone creating a new issue in their text box.

This is a response to https://twitter.com/topjohnwu/status/1042879063403253761

### CODE REVIEW

**Comment by DenyDarko** [comment]
Nice suggestion but let me tell you what's gonna happen.

They'll ignore it as they ignore any other guideline regarding reporting stuff xD

**Comment by SuperSandro2000** [comment]
@DenyDarko it's not gonna help against everything but I am very sure it will help a bit and every little helps.

**Comment by dioni21** [comment]
@DenyDarko It will help those who want to help.

**Comment by Vazkii** [comment]
@krasCGQ This was done on purpose. I'm not exactly sure what it is @topjohnwu would want in here, so I just added the part that I felt was needed from his tweet.

**Pull request closed without merging**
