### PR TITLE
Jjjj

### PR DESCRIPTION
**Pull request by Nashmi97**
Jjiiiiiiiiiiiii

### CODE REVIEW

**Comment by canyie** [comment]
Another spam bot

**Comment by pojavluncher2021** [comment]
> Another spam bot

totally a spam bot

This is a image of F1VM having root access + superuser

**Comment by pojavluncher2021** [comment]
> Another spam bot

By the way are you satisfied with LineageOS?
Try installing  one if you have root <3

**Comment by osm0sis** [comment]
Yep a bot and a real live spammer. Such fun.

**Pull request closed without merging**
