### PR TITLE
Workaround for AVBv2 bootloop on Xiaomi

### PR DESCRIPTION
**Pull request by carey036**
Issues #4447

### CODE REVIEW

**Comment by canyie** [comment]
No comment?

**Comment by osm0sis** [comment]
What are you even hex patching here?

**Comment by carey036** [comment]
> What are you even hex patching here? If it's part of the hacked AVBv2 signature then this is not the right way to fix it and won't be accepted.

that's what i can do, hope someone could find the right way

**Comment by osm0sis** [comment]
Yep, knew this rang a bell! @DarthJabba9 independently confirmed this issue to be about a week or so back, and also found whatever magiskboot is hacking in AVBv2 needs that 03 -> 00 fix to boot on his MIUI devices. @topjohnwu will need to look into what that fix actually means for his vbmeta generation code somewhere here:
https://github.com/topjohnwu/Magisk/search?q=vbmeta
https://github.com/topjohnwu/Magisk/search?q=avb

**Comment by bkerler** [comment]
Confirmed to be a generic issue on Android 11 MTK. With this patch, magisk will work on Realme 8 5G EU as well. Without, it will enter bootloop.

**Comment by osm0sis** [comment]
Just to document exactly where in avb header the 00 -> 03 is, for later further investigation into the avb code for @topjohnwu or others
hxd-avb2
:

**Comment by Displax** [comment]
> Just to document exactly where in avb header the 00 -> 03 is, for later further investigation into the avb code for @topjohnwu or others: 

Same byte that enable verify, as original vbmeta.img`s in devices has.
Most likely, you can simply disable the verify in the vbmeta imgs instead of boot.img.

Sample vbmeta.img from google with verify flag off ( 00 ).
https://developer.android.com/topic/generic-system-image?hl=bn#flash-gsi

**Review by Reynolds251 — APPROVED** [review]

**Comment by osm0sis** [comment]
To reiterate, this PR is not the correct fix for the problem, so will not be merged, but will stay open for now to track the issue since it's more concise than the Issue thread.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/027ec7026252bf1615c19205855ae58a79f1225e#diff-bede474345c35b2e82683e17b88c351ae176ad71013d208e69473c47f212ceadR678 
https://cs.android.com/android/_/android/platform/external/avb/+/ddab37d0073e2108aa57709e9c852e3bd8e56f68:libavb/avb_vbmeta_image.h;l=60;drc=de53827b226bccef7407e4c253b0152e8d9f8e04

`00` will enable verification, do not do this for all devices.

**Comment by vvb2060** [comment]
I think we need a list, do we need to enable verification for all MTK devices?

**Comment by Fox2Code** [comment]
@vvb2060 I just walked though the avb code you sent, apparently there is a way to tell AVB to ignore errors without disabling it.
Maybe doing this trick could allow to fix boot loops while still having AVB enabled and allowing system partition modification.
Code I'm talking about:
https://cs.android.com/android/_/android/platform/external/avb/+/ddab37d0073e2108aa57709e9c852e3bd8e56f68:libavb/avb_cmdline.c;l=324
https://cs.android.com/android/_/android/platform/external/avb/+/ddab37d0073e2108aa57709e9c852e3bd8e56f68:libavb/avb_slot_verify.h;l=90
I did not made more research tho, but it might be a good start.

**Comment by osm0sis** [comment]
This should fix it once merged, try the apk-debug.apk in the Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1432894612

**Comment by osm0sis** [comment]
#4906

**Pull request closed without merging**
