### PR TITLE
Fix app accessibility

### LINKED ISSUE #2125: Add support for Google Talkback assistance in Magisk Manager
Magisk is a really nice tool - but unfortunately blind users can't use it fully since some of the UI elements don't provide textual hints for Google Talkback assistance.

For example: in Magisk Hide there is a list with checkboxes next to the app names - these checkboxes will only be announced as "unnamed control" and without and indication if the checkbox is checked, unchecked or partially checked.

UI elements can provide a textual description for voice assistance in the android:contentDescription property (see https://github.com/arnowelzel/periodical/blob/master/app/src/main/res/layout/main.xml as an example) or by setting the description with `setContentDescription()` (see https://github.com/arnowelzel/periodical/blob/master/app/src/main/java/de/arnowelzel/android/periodical/CalendarCell.java as an example).

### PR DESCRIPTION
**Pull request by canyie**
This pull request is still in progress. Many many components need to be fixed. 
I'm busy recently so this won't be done any time soon

Close #2125

### CODE REVIEW

**Comment by Stuyve** [comment]
Can I use my Magisk now

**Comment by DaUs3103** [comment]
[tsconfig.json](https://github.com/topjohnwu/Magisk/files/15302313/tsconfig.json)

**Comment by DaUs3103** [comment]
[README.md](https://github.com/topjohnwu/Magisk/files/15302316/README.md)

**Comment by canyie** [comment]
Will re-submit the fixes when I have enough time.

**Pull request closed without merging**
