### PR TITLE
Updated Georgian translation

### PR DESCRIPTION
**Pull request by X1nto**

### CODE REVIEW

**Comment by topjohnwu** [comment]
@X1nto please stop changing the file permission to `0755`, there is no need for string resources to have executable permissions

**Comment by X1nto** [comment]
Hi, not sure how this occured since I did not manually change permissions, I'll push a fix

**Comment by X1nto** [comment]
Fixed. Please let me know if there are other problems with PR

**Comment by topjohnwu** [comment]
@X1nto thanks, PR accepted and merged

**Pull request merged**
