### PR TITLE
Add no decompression flag to magiskboot split

### PR DESCRIPTION
**Pull request by osm0sis**
Addresses https://github.com/topjohnwu/Magisk/pull/6597#issuecomment-1518709863

### CODE REVIEW

**Review by yujincheng08 — COMMENTED** [review]
It causes segmentation fault:

> [1]    1782 segmentation fault

**Review by yujincheng08 — CHANGES_REQUESTED** [review]
It causes segmentation fault:

> Program received signal SIGSEGV, Segmentation fault.
0x000000000024c271 in ?? ()

**Comment by osm0sis** [comment]
Thanks, I'll look into it. 🤦‍♂️

**Comment by osm0sis** [comment]
> It causes segmentation fault:
> 
> > Program received signal SIGSEGV, Segmentation fault.
> > 0x000000000024c271 in ?? ()

Worked correctly here, what was your input file?

**Review by yujincheng08 — DISMISSED** [review]
`./magiskboot split -n` will cause SIGSEGV

**Comment by osm0sis** [comment]
Thanks for more info! Reproduced and I'll see about it tonight. 🙂

**Comment by osm0sis** [comment]
Should be good now. Thanks for catching that! I'd looked at the way switches like that are handled in other magiskboot features when I was doing the original changes, but forgot about it after my testing. 😅🤦‍♂️

**Review by yujincheng08 — APPROVED** [review]

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
