### PR TITLE
Don't repack kernels into images that never had a kernel

### PR DESCRIPTION
**Pull request by kerneltoast**
If the image to be repacked doesn't have a kernel in it, then it should not have a kernel shoehorned into the new image. This issue would cause magiskboot to generate broken vendor images upon repacking when a kernel file is present in the same directory as the components to be repacked.

Fix it by never repacking a kernel into an image that didn't have one.

### CODE REVIEW

**Comment by yujincheng08** [comment]
If you don't want the kernel to be packed, remove it.

https://github.com/topjohnwu/Magisk/blob/a82f17c59499ba2c46001c5bc54f8ec5f506e5d8/scripts/boot_patch.sh#L239

**Comment by kerneltoast** [comment]
> If you don't want the kernel to be packed, remove it.
> 
> https://github.com/topjohnwu/Magisk/blob/a82f17c59499ba2c46001c5bc54f8ec5f506e5d8/scripts/boot_patch.sh#L239

magiskboot should not generate garbage images. `mkbootimg.py` explicitly doesn't do this, so why should magiskboot do it too? This is a needless pitfall that is easily fixed by this PR; I don't understand the aversion to this change.

**Comment by kerneltoast** [comment]
Here is proof of the garbage output for a repacked `vendor_kernel_boot.img`:
```
$ ./unpack_bootimg.py --boot_img boot-new.img 
Traceback (most recent call last):
  File "./unpack_bootimg.py", line 563, in <module>
    main()
  File "./unpack_bootimg.py", line 558, in main
    info = unpack_bootimg(args.boot_img, args.out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./unpack_bootimg.py", line 486, in unpack_bootimg
    info = unpack_vendor_boot_image(image_file, output_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./unpack_bootimg.py", line 431, in unpack_vendor_boot_image
    boot_img.read(VENDOR_RAMDISK_NAME_SIZE))[0].decode())
                                                ^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5: invalid continuation byte
```

**Comment by vvb2060** [comment]
Check vendor_boot instead of kernel_size

**Comment by kerneltoast** [comment]
> Check vendor_boot instead of kernel_size

This is a weaker heuristic because vendor ramdisks are optional. It's more robust to check kernel size because the kernel has ever only been located in `boot.img`. If the image did not have a kernel image inside of it, there is no scenario where a kernel image should be introduced after repacking.

**Comment by vvb2060** [comment]
magiskboot uses the current directory as input, so not cleaning the directory before unpacking is undefined behavior, and I think you should fix the script. If the image did not have a kernel image inside of it, there is no scenario where a kernel image should be in the directory.
However, I also agree that invalid format files should not be output.
cc @topjohnwu

**Comment by aviraxp** [comment]
I am for this pr as well.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/53d7cbc11bbb4e417707653db98a916ec2697f7e done

**Comment by kerneltoast** [comment]
Moving one if-statement around was worse than adding a blurb to the documentation indicating that magiskboot might generate a garbage boot image?

**Pull request closed without merging**
