### PR TITLE
Remove MagiskHide FAQ

### PR DESCRIPTION
**Pull request by justkamiii**

### CODE REVIEW

**Comment by justkamiii** [comment]
After seeing that it got removed from the README, shouldn't it also be removed from here?

**Review by KingSleiv94 — COMMENTED** [review]
~~~~

**Review by KingSleiv94 — APPROVED** [review]

**Review by KingSleiv94 — APPROVED** [review]

**Comment by 464551** [comment]
Hi, how to reinstall magisk after factory reset? My phone is bootloop after installing gravity box, then i factory reset my phone, install root checker, and my phone still rooted. How to fix this?

**Comment by justkamiii** [comment]
> Hi, how to reinstall magisk after factory reset? My phone is bootloop after installing gravity box, then i factory reset my phone, install root checker, and my phone still rooted. How to fix this?

This is not the place to ask this buddy, go to the FAQ if your phone is in a bootloop

**Comment by osm0sis** [comment]
Addressed better in #4681

**Pull request closed without merging**
