### PR TITLE
Support KEEPVBMETAFLAG env variable

### LINKED ISSUE #4447: Android 11 MIUI devices need enabled verification in boot.img AVBv2 signature
The Xiaomi device using MT6893 cannot start. After patching the boot, it shows infinite restart. I have disabled the vbmeta test. The models are RedmiNote10Pro and RedmiK40Gaming.  I have used magiskboot extra cpio to prompt me that it failed. When I use Android_image_kitchen, the window flashes and nothing is unpacked. I think his boot has been specially encrypted. If you need it, I will upload the boot file for  the study...
Device: RedmiNote10Pro
Android version:11
Magisk version name: V23
Magisk version code: 23001

### PR DESCRIPTION
**Pull request by vvb2060**
Fixes #4447

### CODE REVIEW

**Comment by carey036** [comment]
it seems that the option of "Preserve vbmeta in boot image" won't appear if android version is 12

**Comment by vvb2060** [comment]
Does MTK devices with Android 12 have this problem too?

**Comment by carey036** [comment]
> Does MTK devices with Android 12 have this problem too?

Yes

**Comment by Gong-Mi** [comment]
小米 联发科1100和1200有这个问题
安卓11到现在安卓12都是这样子

**Comment by vvb2060** [comment]
@carey036 Can you save the log in magisk app and upload?  I'm looking for the MTK prop.

**Comment by carey036** [comment]
[Android 11 log](url)

> @carey036 Can you save the log in magisk app and upload? I'm looking for the MTK prop.

I didn't update to android 12, may Gong-mi could provide Android 12 Verizon.

Here's android 11 version:

https://raw.githubusercontent.com/carey036/OutSide/master/k40gBoot/magisk_log_2021-11-24T22_43_33Z.log

**Comment by vvb2060** [comment]
`ro.mediatek.version.branch` looks good

**Comment by Gong-Mi** [comment]
还需要安卓12的log吗？

**Comment by carey036** [comment]
> 

redmi note 10 pro also has this problem

**Comment by vvb2060** [comment]
@Gong-Mi 有ro.mediatek.version.branch这个prop就行

**Review by Gong-Mi — APPROVED** [review]
<details>



</details>
已经在k40g 安卓12版本上开机

就差合适的说明

还有就是接下来的安卓版本（如安卓13），还能看这个判断选项吗

**Comment by Gong-Mi** [comment]
如果有人用第3rec刷面具，会不会出现意外。
虽然我不喜欢第3方rec。

**Comment by pndwal** [comment]
> > 
> 
> redmi note 10 pro also has this problem

I notice **Redmi Note 10 Pro** is a Qualcomm device, but **Redmi Note 10 Pro (China)** is a MediaTek device.

Please can you confirm (clarity) if **Redmi Note 10 Pro** has this problem. (Perhaps it's just **Redmi Note 10 Pro (China)**?).

**Qualcomm Devices:**
- Redmi Note 10 Pro Max
- Redmi Note 10 Pro
- Redmi Note 10 Pro (India)
- Redmi Note 10 Lite
- Redmi Note 10

**MediaTek Devices:**
- Redmi Note 10 Pro (China)
- Redmi Note 10T 5G
- Redmi Note 10 5G
- Redmi Note 10S

**Comment by carey036** [comment]
> > > 
> > 
> > 
> > redmi note 10 pro also has this problem
> 
> I notice **Redmi Note 10 Pro** is a Qualcomm device, but **Redmi Note 10 Pro (China)** is a MediaTek device.
> 
> Please can you confirm (clarity) if **Redmi Note 10 Pro** does have this problem. (Perhaps it's just **Redmi Note 10 Pro (China)**?).
> 
> **Qualcomm Devices:**
> 
> * Redmi Note 10 Pro Max
> * Redmi Note 10 Pro
> * Redmi Note 10 Pro (India)
> * Redmi Note 10 Lite
> * Redmi Note 10
> 
> **MediaTek Devices:**
> 
> * Redmi Note 10 Pro (China)
> * Redmi Note 10T 5G
> * Redmi Note 10 5G
> * Redmi Note 10S

May it's only redmi note 10 pro (china), i don't know the situation about other place.

**Comment by Gong-Mi** [comment]
> > > 
> > 
> > redmi note 10 pro also has this problem
> 
> I notice **Redmi Note 10 Pro** is a Qualcomm device, but **Redmi Note 10 Pro (China)** is a MediaTek device.
> 
> Please can you confirm (clarity) if **Redmi Note 10 Pro** does have this problem. (Perhaps it's just **Redmi Note 10 Pro (China)**?).
> 
> **Qualcomm Devices:**
> - Redmi Note 10 Pro Max
> - Redmi Note 10 Pro
> - Redmi Note 10 Pro (India)
> - Redmi Note 10 Lite
> - Redmi Note 10
> 
> **MediaTek Devices:**
> - Redmi Note 10 Pro (China)
> - Redmi Note 10T 5G
> - Redmi Note 10 5G
> - Redmi Note 10S

Look at the chip.
Both the MediaTek 1200 and 1100 Xiaomi devices 
have this problem.We have not tested other equipment, and we may still use the previous method.

**Comment by Gong-Mi** [comment]
The reason is that our MediaTek 1100 and 1200 are not able to remove the AVB code of the VB.
As long as you do it, you can't start the machine,  but Boot can start the modified boot by keeping the original AVB identification.
In particular, Xiaomi devices using the MediaTek 1100 and 1200 support the vab system format.

**Comment by vvb2060** [comment]
https://t.me/vvb2060Channel/577


https://cs.android.com/android/platform/superproject/+/master:external/avb/libavb/avb_vbmeta_image.h;l=177;drc=de53827b226bccef7407e4c253b0152e8d9f8e04

```cpp
  /* 120: Flags from the AvbVBMetaImageFlags enumeration. This must be
   * set to zero if the vbmeta image is not a top-level image.
   */
  uint32_t flags;
```

https://cs.android.com/android/platform/superproject/+/master:external/avb/libavb/avb_slot_verify.c;l=785;drc=c0debbfd55f08a755b006550779c23e707d30b6d
```cpp
  /* If we're the toplevel, assign flags so they'll be passed down. */
  if (is_main_vbmeta) {
    toplevel_vbmeta_flags = (AvbVBMetaImageFlags)vbmeta_header.flags;
  } else {
    if (vbmeta_header.flags != 0) {
      ret = AVB_SLOT_VERIFY_RESULT_ERROR_INVALID_METADATA;
      avb_errorv(full_partition_name,
                 ": chained vbmeta image has non-zero flags\n",
                 NULL);
      goto out;
    }
  }
```
If no vbmeta partition exists, the vbmeta inside the boot image, flag must be 0

**Comment by Gong-Mi** [comment]
> @Gong-Mi 有ro.mediatek.version.branch这个prop就行

好像有一个问题 南宫姐

就是每次用优化版本进行ota更新，那个面具都会闪退
虽然面具刷入进去了。

**Comment by Gong-Mi** [comment]
debug版本没有问题，不会闪退，

release版本就有这个问题，而且很大概率可以重复

**Pull request closed without merging**
