### PR TITLE
root service: wait for service to bind before accessing

### LINKED ISSUE #5981: White Blank Modules Tab
Device: Xiaomi Redmi 4A (rolex)
Android version: 12.1
ROM: Nusantara Project
Magisk version name: cacf8736
Magisk version code: 25001

Modules tab in Magisk app is white blanked after the Magisk  app is re-opened sometime and doesn't show the modules list (unless I must go to the other tab of the app first, then modules list can be showed up). It happens both in the canary and the stable version.

Screenshot_20220614-232504_Magisk

[magisk_app_canary_version_logcat.txt](https://github.com/topjohnwu/Magisk/files/8901759/magisk_app_canary_version_logcat.txt)

[magisk_app_stable_version_logcat.txt](https://github.com/topjohnwu/Magisk/files/8901760/magisk_app_stable_version_logcat.txt)

[magisk_log_2022-06-14T23.29.31.log](https://github.com/topjohnwu/Magisk/files/8901762/magisk_log_2022-06-14T23.29.31.log)

I have another question. Can the update.json supports pling.com direct download? Because I uploads my modules to pling.com.

### PR DESCRIPTION
**Pull request by vvb2060**
fix #5981

### CODE REVIEW

**Review by Godsentrather — COMMENTED** [review]
Hia

**Comment by Manoshbi** [comment]
vvb2060:root_service

**Review by ABDAH73 — COMMENTED** [review]
Thanks ♡

**Review by DINDJJDJJSGGWIJXJNSJNSNJDJSBXBBXBBDBXBB — COMMENTED** [review]
شكرا

**Review by azittd5re — COMMENTED** [review]
#

>

**Pull request closed without merging**
