### PR TITLE
Fix early mount on Leagoo T8s

### PR DESCRIPTION
**Pull request by Adm0**
Problem I described [here](https://github.com/topjohnwu/Magisk/issues/844).
Early mount was too early, when mmcblk0 was still missing from /sys/dev/block.

### CODE REVIEW

**Comment by mo123** [comment]
Hope this can be merged soon.
I also have a problem on Rockchip Oreo firmwares where Magisk loads before the system and vendor partitions are mounted. Hope this can also solve my problem.

**Comment by Adm0** [comment]
@mo123 Yes, https://github.com/Adm0/magisk_files

**Comment by mo123** [comment]
> @mo123 Yes, https://github.com/Adm0/magisk_files

Thanks, I'll try it.

**Comment by mo123** [comment]
Using your apps it says in Magisk Manager:
Magisk Manager - Installed 7.2.0 (213) and
Magisk is installed 19.2 (19200) must it not be (19201)?
If I look in the magisk-release.zip, it says the file were last modified 5/5/2019.
I used this app(https://raw.githubusercontent.com/Adm0/magisk_files/master/app-release.apk) to 'Select and patch a file' to patch my boot.img and then unpack/repacked it manually on a PC to work since Magisk doesn't support KRNL repacking and flashed it back.

**Comment by Adm0** [comment]
Magisk Manager differs from the official only by the signature of the application.
19201 is used to upgrade from 19200 using Magisk Manager, using custom upgrade channel.
If I understand correctly, then 5/5/2019 is the date of generation of the signature key. The official is 08/14/2016.
Did this help with the "missing" Magisk?

**Comment by mo123** [comment]
It works now with your changes :)

**Pull request closed without merging**
