### PR TITLE
Partially fixed Japanese translation

### PR DESCRIPTION
**Pull request by s1204IT**
Some sentences have been revised.
Please check it.

### CODE REVIEW

**Comment by AndroPlus-org** [comment]
Line 55 should be "他のアプリがスーパーユーザー権限の要求ダイアログ**を**隠しているため", I think.

**Comment by s1204IT** [comment]
That is correct.
Thank you for pointing that out.

**Comment by s1204IT** [comment]
@AndroPlus-org Please check again.

**Comment by AndroPlus-org** [comment]
> @AndroPlus-org Please check again.

Ok, there's no problem.

**Comment by s1204IT** [comment]
What else can I do to merge?

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
