### PR TITLE
install.md: Mention Heimdall beside Odin

### PR DESCRIPTION
**Pull request by carnhofdaki**
Proven to work with Magisk 25.2, LineageOS 18.1, SM-A520F.

Thank you!

### CODE REVIEW

**Comment by vvb2060** [comment]
This looks to be an all-platform tool, not just Linux

**Comment by BratishkaErik** [comment]
Heimdall supports Windows and macOS too.

**Review by osm0sis — APPROVED** [review]

**Review by osm0sis — APPROVED** [review]

**Comment by osm0sis** [comment]
Reopen to trigger CI.

**Review by Sr-Senpal-Uriel — COMMENTED** [review]
>

**Pull request merged**
