### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by zertyuiop**
Added translation for missing strings. Fixed some lines for better language.

### CODE REVIEW

**Comment by igor-dyatlov** [comment]
@zertyuiop  #1157 two days ago sent a request.

**Comment by zertyuiop** [comment]
@igor-dyatlov Yes, I know, but you have made some errors in your translation. For example "(Core only mode enabled)" is not "(Включен только Core режим)", it stated that the Magisk Core mode enabled, so you need to remove "только" from this line. Another examle: "Скачать один модуль за раз." This message appeares when you try to download two modules at ones so the translation should be "Возможно скачивание лишь одного модуля за раз". You also add dots in the end of some strings, but I think they look ugly. On the other hand, I fixed some translation errors, for example "namespace" is not "именное пространство" but "пространство имён". I also changed translation of "hide" from "скрыть" to "замаскировать", It is more suitable for how Magisk Hide works.

**Comment by igor-dyatlov** [comment]
@zertyuiop точки добавил, так как они есть в оригинальных стрингах. Внес ваши изменения. https://github.com/topjohnwu/Magisk/pull/1157/commits/13d4d4a8608053532e8f94b28f057a357fc40ac4

**Comment by zertyuiop** [comment]
I see you added all my fixes so I can close this request.

**Pull request closed without merging**
