### PR TITLE
scripts: add nand/mtd support to uninstaller

### PR DESCRIPTION
**Pull request by osm0sis**

### CODE REVIEW

**Comment by osm0sis** [comment]
@Msprg can you verify this is working?

**Comment by Msprg** [comment]
Hi, @osm0sis, if you can get me the uninstall.zip which is usually downloaded by manager, I can modify it and try if it does what it should do.
Currently I don't know how to get it myself.

**Comment by osm0sis** [comment]
It's in the Canary folder :+1:

https://github.com/topjohnwu/magisk_files/tree/canary

**Comment by Msprg** [comment]
Oh, okay there it is! 😄  will test and report back ASAP 👍

**Pull request merged**
