### PR TITLE
Use automatic dark mode logo in `README.MD`

### PR DESCRIPTION
**Pull request by flame-0**
Implement automatic dark mode detailed in GitHub's [Basic formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to). This pull request improves accessibility as currently, the text logo is hardly visible when a user is in dark mode theme.

**Preview**
<div align="center">

  Light Mode
  light

  Dark Mode
  dark
</div>

### CODE REVIEW

**Comment by vvb2060** [comment]
Screenshot_20220602-191315

**Comment by flame-0** [comment]
Working fine here,
https://github.com/topjohnwu/Magisk/blob/30e17d3c933241938e324039f739776fd45404b1/README.MD

https://user-images.githubusercontent.com/40175769/171619290-08220119-faa6-4b2b-bfb4-18fab78b17af.mp4

**Comment by vvb2060** [comment]
Screenshot_20220602-193403

**Comment by flame-0** [comment]
> Screenshot_20220602-191315

Looks like this isn't my pull request as shown in the image, 19 hours ago (?). Can you check again, please?

**Comment by vvb2060** [comment]
> the text logo is hardly visible when a user is in dark mode theme.

**Comment by flame-0** [comment]
Can you be more specific?
image

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/pull/5898#issuecomment-1144741791

**Comment by vvb2060** [comment]
Just one color that is clearly visible under any theme, not two images.

**Comment by flame-0** [comment]
This is about **accessibility**. I don't know if you care about that, but I do, really.

**Pull request closed without merging**
