### PR TITLE
Fix syntax error in util_functions.sh

### PR DESCRIPTION
**Pull request by canyie**

### CODE REVIEW

**Comment by osm0sis** [comment]
In addition to the missing then, it's true/false so could just be `elif ! $DATA; then` 👍

**Review by osm0sis — APPROVED** [review]

**Comment by topjohnwu** [comment]
@osm0sis `$DATA` may be an empty string, so we cannot directly do that

**Review by topjohnwu — APPROVED** [review]

**Comment by osm0sis** [comment]
> @osm0sis `$DATA` may be an empty string, so we cannot directly do that

@topjohnwu, oh.. how would that happen? It's only set to true/false in check_data and is treated as such there, and I don't see any other references to $DATA or DATA= anywhere..

https://github.com/topjohnwu/Magisk/blob/master/scripts/util_functions.sh#L510-L520

**Comment by topjohnwu** [comment]
The `check_data` function is only called in recovery and will not be called in the Magisk app.

**Comment by osm0sis** [comment]
Ahh, thanks, that makes more sense now. 🙂

**Pull request merged**
