### PR TITLE
Update Gradle and Correction of artifact name, Modify issue template

### PR DESCRIPTION
**Pull request by s1204IT**

### CODE REVIEW

**Comment by vvb2060** [comment]
about issues template, no need to force the format because there is a bot to enforce it.
about gradlew, 8.3 has been released, why upgrade to rc version?
about ci yml, it breaks avd test

**Comment by s1204IT** [comment]
https://github.com/topjohnwu/Magisk/commit/a1273bc

rc version is set by John Wu

**Comment by s1204IT** [comment]
As for CI, I am not sure enough, so please go through it from now on.

**Comment by vvb2060** [comment]
OK, please open new PRs for them

**Pull request closed without merging**
