### PR TITLE
Add hint: OTA updates not shown until magisk is uninstalled

### PR DESCRIPTION
**Pull request by RAYs3T**
On some devices the OTA update check is reporting "System is up-to-date" even when a new OTA is available. You have to uninstall Magisk first to see the new update.

#2512

### CODE REVIEW

**Comment by osm0sis** [comment]
You would be better off looking at what package needs to be added to the MagiskHide list by default to avoid the issue you describe.

**Comment by linuxandria** [comment]
@osm0sis I'd recommend against that as it may in fact brick your device if it gives you an incremental update. Standard OTA is generally blocked when rooted for good reason. I know on OnePlus devices it'll download the full OTA instead but others restoring stock then updating is probably safest

**Comment by RAYs3T** [comment]
> I suggest maybe saying "On some devices if the proper service isn't magisk hidden then you may have to temporarily unroot

My understanding is that the OTA update dialog is embedded in the system and therefore not listed in hidelist (since it is not a standalone application). If this is the case it would be the only way to unroot first in order to update.

If it is available in the hidelist, should we gather some "examples" of the update dialog package names and suggest to add them in the installation guide?

**Comment by linuxandria** [comment]
@RAYs3T pixels it's done through Google play services, Motorola and OnePlus devices all have a dedicated application (OnePlus is called OPBackup)

But see https://github.com/topjohnwu/Magisk/pull/2513#issuecomment-594398687

**Comment by scottismyname** [comment]
I'm a bit confused....on my Pixel 2XL and Pixel 3 I can't update.  Google play services is already hidden....do additional things need to be hidden?  I tried doing an uninstall (restore images) and re-checking, but it still says my system is up to date.

**Comment by bell18-web** [comment]
@bell18-web

**Pull request closed without merging**
